# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  k9s = {
    pname = "k9s";
    version = "v0.31.4";
    src = fetchFromGitHub {
      owner = "derailed";
      repo = "k9s";
      rev = "v0.31.4";
      fetchSubmodules = false;
      sha256 = "sha256-SB9OuPwRp21FY+cSCf52F6WeWrOqg2bz8rqSaOhRS04=";
    };
  };
}
