# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autobrr = {
    pname = "autobrr";
    version = "v1.70.0";
    src = fetchFromGitHub {
      owner = "autobrr";
      repo = "autobrr";
      rev = "v1.70.0";
      fetchSubmodules = false;
      sha256 = "sha256-znLkrnsmSnnBsSBJvK8m51T9R9O9nDLwWPDUOp9vlxE=";
    };
  };
  jellyfin = {
    pname = "jellyfin";
    version = "v10.11.4";
    src = fetchFromGitHub {
      owner = "jellyfin";
      repo = "jellyfin";
      rev = "v10.11.4";
      fetchSubmodules = false;
      sha256 = "sha256-Hs7G8igW7TJBTYuv83AhN/YhpLcO5pwuU5vYwDUEsUQ=";
    };
  };
  jellyfin-media-player = {
    pname = "jellyfin-media-player";
    version = "v1.12.0";
    src = fetchFromGitHub {
      owner = "jellyfin";
      repo = "jellyfin-media-player";
      rev = "v1.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-IXinyenadnW+a+anQ9e61h+N8vG2r77JPboHm5dN4Iw=";
    };
  };
  jellyfin-plugin-metatube = {
    pname = "jellyfin-plugin-metatube";
    version = "v2025.1102.2200.0";
    src = fetchFromGitHub {
      owner = "metatube-community";
      repo = "jellyfin-plugin-metatube";
      rev = "v2025.1102.2200.0";
      fetchSubmodules = false;
      sha256 = "sha256-OvTD+R7VQvXEK2COJSGC+fnEigH2bSVUBvYfFSF1CxM=";
    };
  };
  jellyfin-web = {
    pname = "jellyfin-web";
    version = "v10.11.4";
    src = fetchFromGitHub {
      owner = "jellyfin";
      repo = "jellyfin-web";
      rev = "v10.11.4";
      fetchSubmodules = false;
      sha256 = "sha256-5MgU9Fw+uiDJLRE1pFHwwfVSnZ47WPeT0Sz4G01jaXs=";
    };
  };
  kometa = {
    pname = "kometa";
    version = "v2.2.2";
    src = fetchFromGitHub {
      owner = "Kometa-Team";
      repo = "Kometa";
      rev = "v2.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-ZM4a0ip2EE67zJgBIeBoh4Ro1OFzZ93TlvS2ab9zi+4=";
    };
  };
  lidarr = {
    pname = "lidarr";
    version = "3.1.0.4875";
    src = fetchurl {
      url = "https://github.com/lidarr/Lidarr/releases/download/v3.1.0.4875/Lidarr.master.3.1.0.4875.linux-core-x64.tar.gz";
      sha256 = "sha256-IPF1rsK5CN4q4GtyVE2uUE79212yqX6k42hm3lO8L6U=";
    };
  };
  navidrome = {
    pname = "navidrome";
    version = "v0.58.5";
    src = fetchFromGitHub {
      owner = "navidrome";
      repo = "navidrome";
      rev = "v0.58.5";
      fetchSubmodules = false;
      sha256 = "sha256-bb6Ak8coEhN4ny79WgZ4DqzjqLbCr1FW/a3w2gfls2M=";
    };
  };
  nzbget = {
    pname = "nzbget";
    version = "v25.4";
    src = fetchFromGitHub {
      owner = "nzbgetcom";
      repo = "nzbget";
      rev = "v25.4";
      fetchSubmodules = false;
      sha256 = "sha256-BP2kNgEDLVpW4TvUW2dToa3rnvGANZw2alBO75Jd2hs=";
    };
  };
  par2cmdline-turbo = {
    pname = "par2cmdline-turbo";
    version = "v1.3.0-20250808";
    src = fetchFromGitHub {
      owner = "nzbgetcom";
      repo = "par2cmdline-turbo";
      rev = "v1.3.0-20250808";
      fetchSubmodules = false;
      sha256 = "sha256-ZP8AI5htmEcxQQtvgShcQ8qNoRL+jBR1BdKS6yyuB/E=";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "2.3.0.5236";
    src = fetchurl {
      url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.3.0.5236/Prowlarr.master.2.3.0.5236.linux-core-x64.tar.gz";
      sha256 = "sha256-UJAO0nS9dqut/vp4un7HB3++KGYqCGCmOGkqh5vBpvo=";
    };
  };
  radarr = {
    pname = "radarr";
    version = "6.0.4.10291";
    src = fetchurl {
      url = "https://github.com/Radarr/Radarr/releases/download/v6.0.4.10291/Radarr.master.6.0.4.10291.linux-core-x64.tar.gz";
      sha256 = "sha256-+pDdm/0GC5Z1ZznXgntR1n0EhJABqlczxOU8X5oIsCM=";
    };
  };
  readarr = {
    pname = "readarr";
    version = "0.4.13.2760";
    src = fetchurl {
      url = "https://github.com/Readarr/Readarr/releases/download/v0.4.13.2760/Readarr.develop.0.4.13.2760.linux-core-x64.tar.gz";
      sha256 = "sha256-bVPUN500vTUdWCz6U1oP0uqLW+LChbCKZMhnYInQ54I=";
    };
  };
  sonarr = {
    pname = "sonarr";
    version = "4.0.16.2944";
    src = fetchurl {
      url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.16.2944/Sonarr.main.4.0.16.2944.linux-x64.tar.gz";
      sha256 = "sha256-HUp0x2PFojbA5utXdTTFseU1heXSzhiaPpAe+1sq38w=";
    };
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
}
