#+title: Todo
* AI stuff
** UIs
https://github.com/lobehub/lobe-chat
https://github.com/zylon-ai/private-gpt
** API
https://localai.io
* Filesystems
** unionfs
mergerfs aufs overlayfs
** pkgs.google-drive-ocamlfuse
Write a home-manager module for this
* k8s
** Use it
https://github.com/argoproj/argo-workflows
https://github.com/kubevela/kubevela
https://github.com/meshery/meshery
https://github.com/helm/chartmuseum
* Cloud services
** auth
https://github.com/nix-community/authentik-nix
** https://unifiedpush.org/
* Cool stuff I want
** Package and make modules
*** TODO [[https://github.com/mujx/hakatime/pull/100][hakatime]]
** stats services
https://wakapi.dev - wakatime replacement with self hosting
** filesystems
https://github.com/netheril96/securefs
** shell things
https://github.com/fastfetch-cli/fastfetch
https://github.com/charmbracelet/gum
https://github.com/DannyBen/bashly
** use modules in nixos
https://docs.searxng.org/
https://docs.gerbera.io/en/stable/index.html
#+begin_src nix
{
  services.searx.enable = true;
  services.mediatomb.enable = true;
}
#+end_src
https://git.sr.ht/~whynothugo/systemd-lock-handler/
https://github.com/dutchcoders/transfer.sh
https://github.com/Vladimir-csp/xdg-terminal-exec
https://github.com/ReimuNotMoe/ydotool
https://github.com/Athou/commafeed
** collect system stats
https://github.com/mann1x/ryzen_monitor_ng
https://gitlab.com/leogx9r/ryzen_smu
https://github.com/AnalogJ/scrutiny
** TODO eliminate perl
#+begin_src nix
{ modulesPath, ... }: {
  imports = [ "${modulesPath}/profiles/perlless.nix" ];
}
#+end_src
** TODO NixOS secrets management
https://github.com/oddlama/agenix-rekey
Find auto-rekey for sops-nix

*** Integrate eval-time secrets with nix-plugins exec
https://oddlama.org/blog/evaluation-time-secrets-in-nix/
** github alternatives
https://radicle.xyz/
https://onedev.io
https://forgejo.org/
https://github.com/harness/gitness
** Nix / flakes
https://github.com/cachix/devenv
https://github.com/sellout/project-manager
https://github.com/hercules-ci/flake-parts
https://github.com/maralorn/nix-output-monitor
** Security
https://github.com/aquasecurity/tracee/
* TODO installers
** DONE Add disko-install script to iso
https://github.com/nix-community/disko/blob/master/docs/disko-install.md
https://github.com/nix-community/disko/blob/master/tests/disko-install/default.nix
** [ ] Reuse parts of https://github.com/nix-community/nixos-images
* home-manager
** TODO modules/services/barrier.nix
** TODO programs/boxxy.nix
** TODO programs.freetube.enable
* chromium extensions
https://github.com/iamadamdev/bypass-paywalls-chrome
* TODO BUGS
---
⛔ Error (sh-mode-local-vars-hook): Error running hook "tree-sitter!" because: (tsc-lang-abi-too-new 14 (13 . 13) /nix/store/wyyb8cmj26v7il37qf9n8s7jl9qbb5mv-emacs-tree-sitter-grammars/langs/bin/bash.so)
⛔ Warning (lsp-mode): Unknown notification: semgrep/rulesRefreshed

Error running timer ‘corfu--auto-complete-deferred’: (error "The connected server(s) does not support method textDocument/completion.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")

--------


Nov 28 10:03:31 oglaroon kernel: ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.28.EC0], AE_NOT_FOUND (20240322/dswload2-162)
Nov 28 10:03:31 oglaroon kernel: fbcon: Taking over console
Nov 28 10:03:31 oglaroon kernel: ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20240322/psobject-220)

Nov 28 10:03:31 oglaroon kernel: pnp 00:03: disabling [io  0xff00-0xfffe] because it overlaps 0000:00:02.2 BAR 13 [io  0xf000-0xffff]

Nov 28 10:03:31 oglaroon kernel: nvme nvme0: missing or invalid SUBNQN field.

Nov 28 10:03:31 oglaroon stage-1-init: [Thu Nov 28 10:03:27 UTC 2024] File descriptor 8 (/dev/console) leaked on lvm invocation. Parent PID 1: /nix/store/fn036gayk8jcxcdim3ig2icvsc86bjmb-ext>
Nov 28 10:03:31 oglaroon stage-1-init: [Thu Nov 28 10:03:27 UTC 2024] File descriptor 9 (/dev/console) leaked on lvm invocation. Parent PID 1: /nix/store/fn036gayk8jcxcdim3ig2icvsc86bjmb-ext>
Nov 28 10:03:31 oglaroon stage-1-init: [Thu Nov 28 10:03:27 UTC 2024] mount: mounting rpool/persist on /persist-tmp-mnt/persist failed: No such file or directory
Nov 28 10:03:31 oglaroon stage-1-init: [Thu Nov 28 10:03:27 UTC 2024] umount: can't unmount /persist-tmp-mnt/persist: Invalid argument
Nov 28 10:03:31 oglaroon stage-1-init: [Thu Nov 28 10:03:27 UTC 2024] cannot open 'rpool/root@blank': dataset does not exist

Nov 28 10:03:32 oglaroon kernel: ccp 0000:03:00.2: ccp: unable to access the device: you might be running a broken BIOS.

Nov 28 10:03:32 oglaroon systemd[1]: Invalid unit name "actkbd@/dev/input/event2.service" escaped as "actkbd@-dev-input-event2.service" (maybe you should use systemd-escape?).

Nov 28 10:03:32 oglaroon systemd[1]: Invalid unit name "actkbd@/dev/input/event0.service" escaped as "actkbd@-dev-input-event0.service" (maybe you should use systemd-escape?).

Nov 28 10:03:32 oglaroon systemd[1]: Invalid unit name "actkbd@/dev/input/event3.service" escaped as "actkbd@-dev-input-event3.service" (maybe you should use systemd-escape?).

Nov 28 10:03:32 oglaroon systemd[1]: Invalid unit name "actkbd@/dev/input/event1.service" escaped as "actkbd@-dev-input-event1.service" (maybe you should use systemd-escape?).

Nov 28 10:03:32 oglaroon systemd[1]: Invalid unit name "actkbd@/dev/input/event5.service" escaped as "actkbd@-dev-input-event5.service" (maybe you should use systemd-escape?).

Nov 28 10:03:32 oglaroon systemd[1]: home.mount: Directory /home to mount over is not empty, mounting anyway.

Nov 28 10:03:32 oglaroon (rpcbind)[2076]: rpcbind.service: Referenced but unset environment variable evaluates to an empty string: RPCBIND_OPTIONS

Nov 28 10:03:33 oglaroon dbus-broker-launch[2154]: Invalid user-name in /nix/store/xs8v1b6xi2pvw8551p1kypbc4nhfhvyl-system-path/share/dbus-1/system.d/pulseaudio-system.conf +27: user="pulse"
Nov 28 10:03:33 oglaroon dbus-broker-launch[2154]: Invalid user-name in /nix/store/drdz2gycz8qrxixw600vfxy1099g1f9r-NetworkManager-openconnect-1.2.10/share/dbus-1/system.d/nm-openconnect-serv
ice.conf +9: user="nm-openconnect"

# journalctl -b0|grep 'Ignoring duplicate name'

Nov 28 10:03:33 oglaroon (uetoothd)[2165]: bluetooth.service: ConfigurationDirectory 'bluetooth' already exists but the mode is different. (File system: 755 ConfigurationDirectoryMode: 555)

Nov 28 10:03:33 oglaroon dpf7iqbmjr6lj3iz66g00c0rbwg0j9sn-audit-disable[2178]: No rules

Nov 28 10:03:34 oglaroon bluetoothd[2165]: src/plugin.c:init_plugin() System does not support asha plugin

Nov 28 10:03:34 oglaroon sm-notify[2736]: Failed to open sm: No such file or directory
Nov 28 10:03:34 oglaroon sm-notify[2736]: Failed to open directory sm.bak: No such file or directory

Nov 28 10:03:34 oglaroon hm-activate-admin[3476]: Failed to load one or more themes from '/home/admin/.config/bat/themes' (reason: 'Invalid syntax theme settings')

Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.720939 [info] permcheck: SECURITY WARNING: directory "/var/lib/private/AdGuardHome" has unexpected permissions 0755; want 0700
Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.720959 [info] permcheck: SECURITY WARNING: directory "/var/lib/private/AdGuardHome/data" has unexpected permissions 0755; want 0700
Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.720970 [info] permcheck: SECURITY WARNING: directory "/var/lib/private/AdGuardHome/data/filters" has unexpected permissions 0755; want 0700
Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.720977 [info] permcheck: SECURITY WARNING: file "/var/lib/private/AdGuardHome/data/sessions.db" has unexpected permissions 0644; want 0600
Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.721038 [info] permcheck: SECURITY WARNING: file "/var/lib/private/AdGuardHome/data/querylog.json" has unexpected permissions 0644; want 0600
Nov 28 10:03:34 oglaroon adguardhome[2808]: 2024/11/28 10:03:34.721057 [info] permcheck: SECURITY WARNING: file "/var/lib/private/AdGuardHome/data/stats.db" has unexpected permissions 0644; want 0600

Nov 28 10:03:35 oglaroon systemd[3856]: Geoclue agent was skipped because of an unmet condition check (ConditionUser=!@system).

Nov 28 10:03:36 oglaroon dbus-broker-launch[4123]: Service file '/run/current-system/sw/share/dbus-1/services/obex-data-server.service' is not named after the D-Bus name 'org.openobex'.

Nov 28 10:03:36 oglaroon tlp[4201]: Error in configuration at CPU_SCALING_GOVERNOR_ON_AC="ondemand": governor not available.

adguardhome journalctl -b0|grep 'does not match safe patterns'
journalctl -b0|grep 'dbus-broker-launch

Nov 28 10:03:43 oglaroon systemd[4451]: hypridle was skipped because of an unmet condition check (ConditionEnvironment=WAYLAND_DISPLAY).

NYXT:
Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
