keys:
  - &vod E3C4C12EDF24CA20F167CC7EE203A151BB3FD1AE
  - &vod_new 382A371CFB344166F69076BE8587AB791475DF76
  - &oglaroon 2657B33B3B8D5B127760A6523FC94255AF7B50F8
  - &asbleg 383717918D3D86D5AC5687AA3E7793D3B1830782
  - &marauder F000AE3CA8A68C0F4392D3D3E19E70EE13C86ECD
creation_rules:
  - path_regex: cells/secrets/sops/envs.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new

  - path_regex: cells/secrets/sops/nixos-common.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *asbleg
          - *marauder
          - *oglaroon
      # - age:
      #     - *oglaroon

  - path_regex: cells/secrets/sops/online-storage-systems.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *asbleg
          - *marauder
          - *oglaroon

  - path_regex: cells/secrets/sops/rclone.conf
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *asbleg
          - *marauder
          - *oglaroon

  - path_regex: cells/secrets/sops/wifi.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new

  - path_regex: cells/secrets/sops/ssh.*$
    key_groups:
      - pgp:
          - *vod
          - *vod_new
