keys:
  - &vod E3C4C12EDF24CA20F167CC7EE203A151BB3FD1AE
  - &vod_new 382A371CFB344166F69076BE8587AB791475DF76
  - &vod_yk5 D299B0B3CCB1D97714DAD6A154CA4193F1572167
  - &oglaroon 2657B33B3B8D5B127760A6523FC94255AF7B50F8
  - &asbleg 383717918D3D86D5AC5687AA3E7793D3B1830782
  - &marauder F000AE3CA8A68C0F4392D3D3E19E70EE13C86ECD
  - &damogran f22401246d122829b59e0ad40f0c6caea0f2b98f
  - &kakrafoon 4366B89962390B5D56DEB342333000D473B9FBFA
creation_rules:
  - path_regex: cells/secrets/sops/envs.yaml
    key_groups:
      - pgp:
          # - *vod
          # - *vod_new
          - *vod_yk5

  - path_regex: cells/secrets/sops/nixos-common.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *asbleg
          - *marauder
          - *oglaroon
          - *damogran
          - *kakrafoon
      # - age:
      #     - *oglaroon

  - path_regex: cells/secrets/sops/online-storage-systems.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *asbleg
          - *marauder
          - *oglaroon
          - *damogran

  - path_regex: cells/secrets/sops/rclone.conf
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *asbleg
          - *marauder
          - *oglaroon
          - *damogran

  - path_regex: cells/secrets/sops/wifi.yaml
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5

  # - path_regex: cells/secrets/sops/ssh.*$
  #   key_groups:
  #     - pgp:
  #         - *vod
  #         - *vod_new
  #         - *vod_yk5

  # zerotier keys
  - path_regex: cells/secrets/sops/zerotier/oglaroon/ca4d6753c1
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *oglaroon

  - path_regex: cells/secrets/sops/zerotier/kakrafoon/ba8ec53f7a
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *kakrafoon

  - path_regex: cells/secrets/sops/zerotier/asbleg/edc7b5c56e
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *asbleg

  - path_regex: cells/secrets/sops/zerotier/marauder/1747defb79
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *marauder

  - path_regex: cells/secrets/sops/zerotier/damogran/cb324d4155
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *damogran

  - path_regex: cells/secrets/sops/powerdns
    key_groups:
      - pgp:
          - *vod
          - *vod_new
          - *vod_yk5
          - *asbleg
          - *marauder
          - *oglaroon
          - *damogran
          - *kakrafoon
