keys:
  - &vod E3C4C12EDF24CA20F167CC7EE203A151BB3FD1AE
  # - &oglaroon
  - &asbleg 383717918D3D86D5AC5687AA3E7793D3B1830782
creation_rules:
  - path_regex: cells/secrets/sops/envs.yaml
    key_groups:
      - pgp:
          - *vod

  - path_regex: cells/secrets/sops/nixos-common.yaml
    key_groups:
      - pgp:
          - *vod
          - *asbleg
      # - age:
      #     - *oglaroon

  - path_regex: cells/secrets/sops/wifi.yaml
    key_groups:
      - pgp:
          - *vod

  - path_regex: cells/secrets/sops/ssh.*$
    key_groups:
      - pgp:
          - *vod
