# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/lib/cfg/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# nixos-generators with custom format
generate format-path name:
    nixos-generate --format-path ${PRJ_ROOT}/cells/nixos/generators/{{ format-path }}.nix --system x86_64-linux --flake .#{{ name }}

# Colmena [action] [name] Machine
machine action name:
    colmena {{ action }} --on {{ name }}
