# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ledgerblue = {
    pname = "ledgerblue";
    version = "6a39324368a5406b37c38ffc53c3a4ede0b6ce0f";
    src = fetchgit {
      url = "https://github.com/LedgerHQ/blue-loader-python";
      rev = "6a39324368a5406b37c38ffc53c3a4ede0b6ce0f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-redSCVuC7VpCPB6qDrq7TG4EfIX8mJtFHZ8JDlhH4yI=";
    };
    date = "2025-07-30";
  };
  python-gnupg = {
    pname = "python-gnupg";
    version = "0.5.4";
    src = fetchFromGitHub {
      owner = "vsajip";
      repo = "python-gnupg";
      rev = "0.5.4";
      fetchSubmodules = false;
      sha256 = "sha256-TGf9yRGJcx8K/8SrJ8UZEVpqO8HgTgAngSI2pyshOrk=";
    };
  };
}
