# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ledgerblue = {
    pname = "ledgerblue";
    version = "a2eb366bd859fa94c2cb7e7a390a40934e69495c";
    src = fetchgit {
      url = "https://github.com/LedgerHQ/blue-loader-python";
      rev = "a2eb366bd859fa94c2cb7e7a390a40934e69495c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-k7j0S7ukIwkil7KCp4uDfi+rmRfxmJ4XSRLFcajGZbE=";
    };
    date = "2024-05-21";
  };
  python-gnupg = {
    pname = "python-gnupg";
    version = "0.5.3";
    src = fetchFromGitHub {
      owner = "vsajip";
      repo = "python-gnupg";
      rev = "0.5.3";
      fetchSubmodules = false;
      sha256 = "sha256-K25W0RkK+yH+E3t3w1sAB1nHufUaOfSr6QSsMvZBFco=";
    };
  };
}
