# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  getoptions = {
    pname = "getoptions";
    version = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
    src = fetchFromGitHub {
      owner = "ko1nksm";
      repo = "getoptions";
      rev = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
      fetchSubmodules = false;
      sha256 = "sha256-MJ4UUDmd+yykvRjgxx8MRZwlLNauDb8Bh8lS0QvkG+U=";
    };
    date = "2022-07-03";
  };
  lorri = {
    pname = "lorri";
    version = "7db4a3b168c670366905c97ef266996a7d772bc1";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "lorri";
      rev = "7db4a3b168c670366905c97ef266996a7d772bc1";
      fetchSubmodules = false;
      sha256 = "sha256-xXQfY124ZCMfHOa3ejm8aUU+OnwcZYlYG8X2nphWYXI=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2024-04-08";
  };
  nix-index = {
    pname = "nix-index";
    version = "b5fcd082f474d41b11e01aa8f8f3131ae40f8952";
    src = fetchFromGitHub {
      owner = "bennofs";
      repo = "nix-index";
      rev = "b5fcd082f474d41b11e01aa8f8f3131ae40f8952";
      fetchSubmodules = false;
      sha256 = "sha256-UJenH6w80dGVDTA2aXbstj10x1i+fkEhJbamO0jotiE=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-12-06";
  };
  rainbowsh = {
    pname = "rainbowsh";
    version = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
    src = fetchFromGitHub {
      owner = "xr09";
      repo = "rainbow.sh";
      rev = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
      fetchSubmodules = false;
      sha256 = "sha256-F+Nabc/Fe5ET6lSkdll5YH/mEpKp3OlpaGk+u0rQpPQ=";
    };
    date = "2022-08-24";
  };
  shellspec = {
    pname = "shellspec";
    version = "f800240b606ed8d60f27ca687400836c0083e76a";
    src = fetchFromGitHub {
      owner = "shellspec";
      repo = "shellspec";
      rev = "f800240b606ed8d60f27ca687400836c0083e76a";
      fetchSubmodules = false;
      sha256 = "sha256-PyZBc7bmycV02nTpoDaA40m4DA1IuDmb/eCd3+RAp0o=";
    };
    date = "2022-05-04";
  };
  shflags = {
    pname = "shflags";
    version = "96694d58ce92065fdd8f8761d930765cb9a8d066";
    src = fetchFromGitHub {
      owner = "kward";
      repo = "shflags";
      rev = "96694d58ce92065fdd8f8761d930765cb9a8d066";
      fetchSubmodules = false;
      sha256 = "sha256-IJJEi8xmIco/IuN9LSf6qMacsG6jHQek9F0dPKEwviI=";
    };
    date = "2023-08-24";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "41be86cd59b53913941b1d207273389332c9b502";
    src = fetchFromGitHub {
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "41be86cd59b53913941b1d207273389332c9b502";
      fetchSubmodules = false;
      sha256 = "sha256-5nlku/JUs1YnchOGvsle7rF96b3DteMuxZhSzoNvDGY=";
    };
    date = "2024-04-01";
  };
  zsh-plugin_any-nix-shell = {
    pname = "zsh-plugin_any-nix-shell";
    version = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
    src = fetchFromGitHub {
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
      fetchSubmodules = false;
      sha256 = "sha256-j1DE0WTBGLmBLoPmqST9YVj9Jc4Mp8WXQILmPBzRlbM=";
    };
    date = "2023-11-08";
  };
  zsh-plugin_aw-watcher-shell = {
    pname = "zsh-plugin_aw-watcher-shell";
    version = "9915c40ba472f3c50c944bcc0e2fa96f982defb9";
    src = fetchgit {
      url = "https://github.com/voobscout/aw-watcher-shell";
      rev = "9915c40ba472f3c50c944bcc0e2fa96f982defb9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-72aQ5N5L14mwJ8RB50p/swi6wXhPGYRYJ/Q8CUdP4wE=";
    };
    date = "2023-12-06";
  };
  zsh-plugin_clipboard = {
    pname = "zsh-plugin_clipboard";
    version = "3e996c5b54b16029fefe8b40648371634b1a7510";
    src = fetchgit {
      url = "https://github.com/zpm-zsh/clipboard";
      rev = "3e996c5b54b16029fefe8b40648371634b1a7510";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BaYYzl6JArfPWASJtzk44scGejwgyT5+W94ugVDCV3I=";
    };
    date = "2024-01-03";
  };
  zsh-plugin_fast-syntax-highlighting = {
    pname = "zsh-plugin_fast-syntax-highlighting";
    version = "3dea11a9018061e6e3a77e529b79e5654679d3a0";
    src = fetchFromGitHub {
      owner = "z-shell";
      repo = "F-Sy-H";
      rev = "3dea11a9018061e6e3a77e529b79e5654679d3a0";
      fetchSubmodules = false;
      sha256 = "sha256-AEeGEx2vyyHVS92Nla7XoqSx3rTpQHYwPMrK1jFH1Mg=";
    };
    date = "2023-12-17";
  };
  zsh-plugin_k = {
    pname = "zsh-plugin_k";
    version = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
    src = fetchgit {
      url = "https://github.com/supercrabtree/k";
      rev = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-32rJjBzqS2e6w/L78KMNwQRg4E3sqqdAmb87XEhqbRQ=";
    };
    date = "2018-09-09";
  };
  zsh-plugin_nix-zsh-completions = {
    pname = "zsh-plugin_nix-zsh-completions";
    version = "6e782b97091b07eb849b58953eb200ccc56ef833";
    src = fetchFromGitHub {
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "6e782b97091b07eb849b58953eb200ccc56ef833";
      fetchSubmodules = false;
      sha256 = "sha256-bgbMc4HqigqgdkvUe/CWbUclwxpl17ESLzCIP8Sz+F8=";
    };
    date = "2024-03-14";
  };
  zsh-plugin_oh-my-zsh = {
    pname = "zsh-plugin_oh-my-zsh";
    version = "31f2025e0fa963788655fe197e0179c47588b175";
    src = fetchgit {
      url = "https://github.com/robbyrussell/oh-my-zsh";
      rev = "31f2025e0fa963788655fe197e0179c47588b175";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-tQD7H1f2KKSo647rWtplSIoBUiiNWAvAxSWw6e26BNk=";
    };
    date = "2024-04-12";
  };
  zsh-plugin_tipz = {
    pname = "zsh-plugin_tipz";
    version = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
    src = fetchgit {
      url = "https://github.com/molovo/tipz";
      rev = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oFZJwHYDfK4f53lhcZg6PCw2AgHxFC0CRiqiinKZz8k=";
    };
    date = "2018-05-03";
  };
  zsh-plugin_zsh-256color = {
    pname = "zsh-plugin_zsh-256color";
    version = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
    src = fetchgit {
      url = "https://github.com/chrissicool/zsh-256color";
      rev = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-P/pbpDJmsMSZkNi5GjVTDy7R+OxaIVZhb/bEnYQlaLo=";
    };
    date = "2022-09-13";
  };
  zsh-plugin_zsh-autoenv = {
    pname = "zsh-plugin_zsh-autoenv";
    version = "e9809c1bd28496e025ca05576f574e08e93e12e8";
    src = fetchgit {
      url = "https://github.com/Tarrasch/zsh-autoenv";
      rev = "e9809c1bd28496e025ca05576f574e08e93e12e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SxDRldr9eqRtPQ3IWFKX0Q+vEG8Ry34PNRZ/I16aju0=";
    };
    date = "2018-09-14";
  };
  zsh-plugin_zsh-autopair = {
    pname = "zsh-plugin_zsh-autopair";
    version = "2ec3fd3c9b950c01dbffbb2a4d191e1d34b8c58a";
    src = fetchgit {
      url = "https://github.com/hlissner/zsh-autopair";
      rev = "2ec3fd3c9b950c01dbffbb2a4d191e1d34b8c58a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Y7fkpvCOC/lC2CHYui+6vOdNO8dNHGrVYTGGNf9qgdg=";
    };
    date = "2024-03-08";
  };
  zsh-plugin_zsh-completions = {
    pname = "zsh-plugin_zsh-completions";
    version = "7e781997719234fd0eaac100d377b27628678062";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-completions";
      rev = "7e781997719234fd0eaac100d377b27628678062";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Lq6aCYsakg4zxiGgJRyK+FgewLSI6RZfIJzrBr7cJGQ=";
    };
    date = "2024-04-15";
  };
  zsh-plugin_zsh-history-substring-search = {
    pname = "zsh-plugin_zsh-history-substring-search";
    version = "8dd05bfcc12b0cd1ee9ea64be725b3d9f713cf64";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-history-substring-search";
      rev = "8dd05bfcc12b0cd1ee9ea64be725b3d9f713cf64";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-houujb1CrRTjhCc+dp3PRHALvres1YylgxXwjjK6VZA=";
    };
    date = "2023-11-23";
  };
  zsh-plugin_zsh-syntax-highlighting = {
    pname = "zsh-plugin_zsh-syntax-highlighting";
    version = "e0165eaa730dd0fa321a6a6de74f092fe87630b0";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-syntax-highlighting";
      rev = "e0165eaa730dd0fa321a6a6de74f092fe87630b0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Vt2yKzMRJ34FBFPKrN+GJBZYmBt5ASArrs1dkZcIQmI=";
    };
    date = "2024-01-06";
  };
}
