[atuin]
src.github = "atuinsh/atuin"
src.use_latest_release = true
fetch.github = "atuinsh/atuin"
extract = ["Cargo.lock"]
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[spaceship-prompt]
# Spaceship is a minimalistic, powerful and extremely customizable Zsh prompt
src.git = "https://github.com/spaceship-prompt/spaceship-prompt"
fetch.github = "spaceship-prompt/spaceship-prompt"

[shflags]
# shFlags is a port of the Google gflags library for Unix shell
src.git = "https://github.com/kward/shflags"
fetch.github = "kward/shflags"

[shellspec]
# ShellSpec is a full-featured BDD unit testing framework
src.git = "https://github.com/shellspec/shellspec"
fetch.github = "shellspec/shellspec"

[getoptions]
# An elegant option parser for shell scripts (full support for all POSIX shells)
src.git = "https://github.com/ko1nksm/getoptions"
fetch.github = "ko1nksm/getoptions"

[rainbowsh]
# Simple colors for your bash scripts
src.git = "https://github.com/xr09/rainbow.sh"
fetch.github = "xr09/rainbow.sh"

[nix-index]
# nix-index is a tool to quickly locate the package providing a certain file in nixpkgs.
src.git = "https://github.com/bennofs/nix-index"
fetch.github = "bennofs/nix-index"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[lorri]
# lorri is a nix-shell replacement for project development
src.git = "https://github.com/nix-community/lorri"
src.branch = "canon"
fetch.github = "nix-community/lorri"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

### ZSH plugins
[zsh-plugin_any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
src.branch = "master"
fetch.github = "haslersn/any-nix-shell"

[zsh-plugin_nix-zsh-completions]
src.git = "https://github.com/spwhitt/nix-zsh-completions"
src.branch = "master"
fetch.github = "spwhitt/nix-zsh-completions"

[zsh-plugin_fast-syntax-highlighting]
src.git = "https://github.com/z-shell/F-Sy-H"
fetch.github = "z-shell/F-Sy-H"

[zsh-plugin_aw-watcher-shell]
src.git = "https://github.com/voobscout/aw-watcher-shell"
fetch.git = "https://github.com/voobscout/aw-watcher-shell"

[zsh-plugin_zsh-history-substring-search]
src.git = "https://github.com/zsh-users/zsh-history-substring-search"
fetch.git = "https://github.com/zsh-users/zsh-history-substring-search"

[zsh-plugin_zsh-completions]
src.git = "https://github.com/zsh-users/zsh-completions"
fetch.git = "https://github.com/zsh-users/zsh-completions"

[zsh-plugin_clipboard]
src.git = "https://github.com/zpm-zsh/clipboard"
fetch.git = "https://github.com/zpm-zsh/clipboard"

[zsh-plugin_k]
src.git = "https://github.com/supercrabtree/k"
fetch.git = "https://github.com/supercrabtree/k"

[zsh-plugin_oh-my-zsh]
src.git = "https://github.com/robbyrussell/oh-my-zsh"
fetch.git = "https://github.com/robbyrussell/oh-my-zsh"

[zsh-plugin_zsh-syntax-highlighting]
src.git = "https://github.com/zsh-users/zsh-syntax-highlighting"
fetch.git = "https://github.com/zsh-users/zsh-syntax-highlighting"

[zsh-plugin_tipz]
src.git = "https://github.com/molovo/tipz"
fetch.git = "https://github.com/molovo/tipz"

[zsh-plugin_zsh-autopair]
src.git = "https://github.com/hlissner/zsh-autopair"
fetch.git = "https://github.com/hlissner/zsh-autopair"

[zsh-plugin_zsh-256color]
src.git = "https://github.com/chrissicool/zsh-256color"
fetch.git = "https://github.com/chrissicool/zsh-256color"

[zsh-plugin_zsh-autoenv]
src.git = "https://github.com/Tarrasch/zsh-autoenv"
fetch.git = "https://github.com/Tarrasch/zsh-autoenv"

[dircolors-solarized]
src.git = "https://github.com/seebi/dircolors-solarized"
fetch.git = "https://github.com/seebi/dircolors-solarized"
