jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
    parameters:
      host:
        type: string
    resource_class: arm.large
    steps:
    - nix/install:
        channels: nixpkgs=https://nixos.org/channels/nixos-24.05
        extra-conf: "experimental-features = flakes nix-command\n"
    - nix/install-cachix
    - checkout
    - run:
        command: "cachix use nix-community\ncachix use mic92\ncachix use nrdxp\ncachix
          use njk\n./.ci/install-nix.sh > /tmp/store-path-pre-build\n"
        name: Setup Cachix repos
    - run:
        command: "nix build \".#nixosConfigurations.<< parameters.host >>.config.system.build.toplevel\"\
          \n"
        name: Build system
    - run:
        command: "./.ci/push-paths.sh cachix \"--compression-method xz --compression-level
          9 --jobs 8\" njk \"\"  \"\"\n"
        name: Push cache
        no_output_timeout: 30m
orbs:
  nix: eld/nix@1.1.1
version: '2.1'
workflows:
  version: '2'
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
            - auto/upgrade-dependencies
        matrix:
          parameters:
            host:
            - nixos-damogran
