jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
    parameters:
      host:
        type: string
    resource_class: arm.large
    steps:
    - nix/install:
        channels: nixpkgs=https://nixos.org/channels/nixos-24.05
        extra-conf: 'experimental-features = flakes nix-command

          '
    - nix/install-cachix
    - checkout
    - run:
        command: 'cachix use nix-community

          cachix use mic92

          cachix use nrdxp

          cachix use njk

          ./.ci/install-nix.sh > /tmp/store-path-pre-build

          '
        name: Setup Cachix repos
    - run:
        command: 'nix build ".#nixosConfigurations.<< parameters.host >>.config.system.build.toplevel"

          '
        name: Build system
    - run:
        command: './.ci/push-paths.sh cachix "--compression-method xz --compression-level
          9 --jobs 8" njk ""  ""

          '
        name: Push cache
        no_output_timeout: 30m
orbs:
  nix: eld/nix@1.1.1
version: '2.1'
workflows:
  version: '2'
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
            - auto/upgrade-dependencies
        matrix:
          parameters:
            host:
            - nixos-damogran
