# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
      fetchSubmodules = false;
      sha256 = "sha256-EYhFrOo0j0JSNTdcZCbyM0iLxaymUXi1u6jZy8lTOaY=";
    };
    date = "2023-12-06";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "63eb19a10e4262c529f1b205ef61d69055350f49";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "63eb19a10e4262c529f1b205ef61d69055350f49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x6CrLGslawBtixdXDyp1U3i5yY8tkuI75LkHvOyt6YI=";
    };
    date = "2023-07-31";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sR0982CcdMXtn+hCRrvm3F2+60/JxQrGi3rEuioFEjI=";
    };
    date = "2023-09-09";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "ee296163e53f44c92fc8869a60bcfdd68376581a";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "ee296163e53f44c92fc8869a60bcfdd68376581a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-U9fOY7G1eC6xHTIZ4290WcY61+ZFzmNY+AJsraAbSZ8=";
    };
    date = "2023-12-12";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "1542d76909636bf8804dd9c770f28818a897cfdc";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "1542d76909636bf8804dd9c770f28818a897cfdc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Vt+3OZM89dyLKjFnODWNHLDwrURXAtY5MFugyfEMbho=";
    };
    date = "2024-01-02";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "03d692f129633e3bf0bd100d91b3ebf3f77db6d1";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "03d692f129633e3bf0bd100d91b3ebf3f77db6d1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-naCexnEewgyi9UVPZ7djSR4X4zKQvLYT1YVn/baubKs=";
    };
    date = "2023-12-08";
  };
  jinx = {
    pname = "jinx";
    version = "3e61f60b7c450cfe867178c7f9b77d56dd9142c0";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "3e61f60b7c450cfe867178c7f9b77d56dd9142c0";
      fetchSubmodules = false;
      sha256 = "sha256-Cxw6rCMfiq/3Rp65bN2aAZ+rV8bBsf9YVSVNzksemAI=";
    };
    date = "2024-01-02";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "dfc5c3210ec1d6c421ef38e51e30f568ad4a3a54";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "dfc5c3210ec1d6c421ef38e51e30f568ad4a3a54";
      fetchSubmodules = false;
      sha256 = "sha256-QKuOBNRGpN83d+/8rsSTRhtAP1f/oYMNEtkZuBVqlj4=";
    };
    date = "2024-01-03";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "2dddc6e9ca33be211675afca3896fd661fc38a0c";
    src = fetchFromGitHub {
      owner = "remi-gelinas";
      repo = "nix-ts-mode";
      rev = "2dddc6e9ca33be211675afca3896fd661fc38a0c";
      fetchSubmodules = false;
      sha256 = "sha256-MGbkSqdImoIH/TIzMy5WHiS7sEb2NzOH+dqHTUg+9Kg=";
    };
    date = "2023-11-08";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
  spacemacs = {
    pname = "spacemacs";
    version = "3292ba1cdf4963dfa1cd3c4724e6a05bbd2c8e98";
    src = fetchgit {
      url = "https://github.com/syl20bnr/spacemacs";
      rev = "3292ba1cdf4963dfa1cd3c4724e6a05bbd2c8e98";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-L9WaxkwXDi1xNIvSr7FObdsF8Q4JjyOMmkT5IJK7dP4=";
    };
    date = "2024-01-03";
  };
}
