# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "7a413efecee5bb0b718708611b185caf5580a801";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "7a413efecee5bb0b718708611b185caf5580a801";
      fetchSubmodules = false;
      sha256 = "sha256-MrWqTes9iwrRu1zKNh4I5L6oOyRE2Huri8nEQgfvjTQ=";
    };
    date = "2023-11-20";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "63eb19a10e4262c529f1b205ef61d69055350f49";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "63eb19a10e4262c529f1b205ef61d69055350f49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x6CrLGslawBtixdXDyp1U3i5yY8tkuI75LkHvOyt6YI=";
    };
    date = "2023-07-31";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sR0982CcdMXtn+hCRrvm3F2+60/JxQrGi3rEuioFEjI=";
    };
    date = "2023-09-09";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "65818c493f100a78bf55f5a0fe83f29521621b15";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "65818c493f100a78bf55f5a0fe83f29521621b15";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SW4KuLbGx54/WsFvwNtqG3Sm8HPFytc+9VUZ5+Geo8U=";
    };
    date = "2023-11-06";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "61ddc2d6aae25b490213c13a14c791c48463bf4a";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "61ddc2d6aae25b490213c13a14c791c48463bf4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ijlverhwgOp1TUxdDYr7FoouNyRiRhP4BbIw2xblPJo=";
    };
    date = "2023-11-27";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "a89d4b7df556bb8b309d1c23e0b60404e750f156";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "a89d4b7df556bb8b309d1c23e0b60404e750f156";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-nONYdoZEJIgB03yYC7eTV3r4XFr3F9ImD4GDj7Xtxvg=";
    };
    date = "2023-12-01";
  };
  jinx = {
    pname = "jinx";
    version = "2533991bfe9da75aa6adad73770fe5b196ea0bb1";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "2533991bfe9da75aa6adad73770fe5b196ea0bb1";
      fetchSubmodules = false;
      sha256 = "sha256-5UMX8TdZdlLhCX6U+xrIRigC79T+voj1aF8Av+K5NAM=";
    };
    date = "2023-12-01";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "4150b07410f84cc19f9682af74ea1a6632f85d99";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "4150b07410f84cc19f9682af74ea1a6632f85d99";
      fetchSubmodules = false;
      sha256 = "sha256-6aFXBLnzmjItE1XVwYslgIjrv50EXypW2cifE6MkOsU=";
    };
    date = "2023-11-30";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "2dddc6e9ca33be211675afca3896fd661fc38a0c";
    src = fetchFromGitHub {
      owner = "remi-gelinas";
      repo = "nix-ts-mode";
      rev = "2dddc6e9ca33be211675afca3896fd661fc38a0c";
      fetchSubmodules = false;
      sha256 = "sha256-MGbkSqdImoIH/TIzMy5WHiS7sEb2NzOH+dqHTUg+9Kg=";
    };
    date = "2023-11-08";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
  spacemacs = {
    pname = "spacemacs";
    version = "8f7019340ec38c2cd70df37739a0adf77ff1e788";
    src = fetchgit {
      url = "https://github.com/syl20bnr/spacemacs";
      rev = "8f7019340ec38c2cd70df37739a0adf77ff1e788";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-SjOogJeZp1gN41DoK/1sPnlNhMvDG8ohM6okaAW02sk=";
    };
    date = "2023-11-26";
  };
}
