# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider-chat = {
    pname = "aider-chat";
    version = "v0.85.0";
    src = fetchFromGitHub {
      owner = "Aider-AI";
      repo = "aider";
      rev = "v0.85.0";
      fetchSubmodules = false;
      sha256 = "sha256-ZYjDRu4dAOkmz+fMOG8KU6y27RI/t3iEoTSUebundqo=";
    };
  };
  dspy = {
    pname = "dspy";
    version = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
    src = fetchgit {
      url = "https://git.smart-cactus.org/ben/dspy-nix";
      rev = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qKEeM2SbQ5jpYVkRU00Zkdzyzjpek7fcoFWLmsVoRsk=";
    };
    flake = "true";
    date = "2025-01-12";
  };
  kestra = {
    pname = "kestra";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "kestra/kestra";
      imageDigest = "sha256:70edd58af6074e1e47447e1fb920791615a43b072f59633279ba2e4c0e744bfa";
      sha256 = "sha256-pLLN2OUv6RPe5QXObA4GD4jopXFQk0Z8Z8grapX3/VI=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  lobe-chat = {
    pname = "lobe-chat";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "lobehub/lobe-chat";
      imageDigest = "sha256:22b423ef6b9fd205c8875d8470d3941b97fd24801736a17b76ad618556b316ee";
      sha256 = "sha256-2muZ/k5+/YrZEOcUKYQTtxe4rYRAjGeWqYJxrMEfEM0=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  metagpt = {
    pname = "metagpt";
    version = "5333651c1a3023720c427af6d737a5784b2163de";
    src = fetchgit {
      url = "https://github.com/infinidim-enterprises/metagpt.nix";
      rev = "5333651c1a3023720c427af6d737a5784b2163de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+LKsmQNJKmWlefwtVwUI28xGAvgpAtBkpZU9feTuiPA=";
    };
    flake = "true";
    date = "2025-08-09";
  };
  n8n = {
    pname = "n8n";
    version = "n8n@1.105.4";
    src = fetchurl {
      url = "https://github.com/n8n-io/n8n/archive/n8n@1.105.4.tar.gz";
      name = "n8n.tar.gz";
      sha256 = "sha256-lzBX5oUiv92hEqITH5KGJCu8PbgcdPLB5k1/Jvk0oKI=";
    };
  };
}
