# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider-chat = {
    pname = "aider-chat";
    version = "v0.84.0";
    src = fetchFromGitHub {
      owner = "Aider-AI";
      repo = "aider";
      rev = "v0.84.0";
      fetchSubmodules = false;
      sha256 = "sha256-TOlqwJM9wIAURSimuh9mysYDwgH9AfFev8jY9elLNk8=";
    };
  };
  dspy = {
    pname = "dspy";
    version = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
    src = fetchgit {
      url = "https://git.smart-cactus.org/ben/dspy-nix";
      rev = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qKEeM2SbQ5jpYVkRU00Zkdzyzjpek7fcoFWLmsVoRsk=";
    };
    flake = "true";
    date = "2025-01-12";
  };
  kestra = {
    pname = "kestra";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "kestra/kestra";
      imageDigest = "sha256:6622e3288da7a637029f27b438b8471268490442cfa1c160e14b971d7220ec3c";
      sha256 = "sha256-Cq9Rv/OfKYZgoZQi4x8KRQEZu1XQeUZWf/xK6SjeEjs=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  lobe-chat = {
    pname = "lobe-chat";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "lobehub/lobe-chat";
      imageDigest = "sha256:d27484d7c858ec2b1d553851f332a7543c3affed5dc4b2aa2af695f4c26f587e";
      sha256 = "sha256-gGWc3Pk8sTa3FnwXns9pg2QqMAb1ARrXuB5Z1pUKRu8=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  metagpt = {
    pname = "metagpt";
    version = "711bd63d942d0bfe3fd0c519e23f35aca657afd8";
    src = fetchgit {
      url = "https://github.com/infinidim-enterprises/metagpt.nix";
      rev = "711bd63d942d0bfe3fd0c519e23f35aca657afd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Co7jjETUjUwgHHj4B4LDbkx1a4ObktXorweYwk7yuWc=";
    };
    flake = "true";
    date = "2025-06-01";
  };
  n8n = {
    pname = "n8n";
    version = "n8n@1.94.1";
    src = fetchurl {
      url = "https://github.com/n8n-io/n8n/archive/n8n@1.94.1.tar.gz";
      name = "n8n.tar.gz";
      sha256 = "sha256-/bxow83jwZtnwJonNkNNGbRUXlFDQ/J2e03c1/iJaYg=";
    };
  };
}
