# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider-chat = {
    pname = "aider-chat";
    version = "v0.85.0";
    src = fetchFromGitHub {
      owner = "Aider-AI";
      repo = "aider";
      rev = "v0.85.0";
      fetchSubmodules = false;
      sha256 = "sha256-ZYjDRu4dAOkmz+fMOG8KU6y27RI/t3iEoTSUebundqo=";
    };
  };
  dspy = {
    pname = "dspy";
    version = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
    src = fetchgit {
      url = "https://git.smart-cactus.org/ben/dspy-nix";
      rev = "334b07ea0203a5149f0c5ee9572569ffbbc8e711";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qKEeM2SbQ5jpYVkRU00Zkdzyzjpek7fcoFWLmsVoRsk=";
    };
    flake = "true";
    date = "2025-01-12";
  };
  kestra = {
    pname = "kestra";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "kestra/kestra";
      imageDigest = "sha256:cafc46f9c41367b739e35466c9500e8e2cbab1b4ec83e114c10bc7de072481d1";
      sha256 = "sha256-1pV7xsgu6Tm//nz4Wbs837mGpwvLVJSU0jMnkHpiGy4=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  lobe-chat = {
    pname = "lobe-chat";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "lobehub/lobe-chat";
      imageDigest = "sha256:0988e259ea8a398c9e923c915d62932c8500ed6b3019ca0da3b939df907e8062";
      sha256 = "sha256-QaIXL75eMWVJ0dOK1CzCAsd37XaKC1cu3yNOrZkq4Pw=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  metagpt = {
    pname = "metagpt";
    version = "ee778dddf845da046b6cc1f9985f08259f54715c";
    src = fetchgit {
      url = "https://github.com/infinidim-enterprises/metagpt.nix";
      rev = "ee778dddf845da046b6cc1f9985f08259f54715c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-HO25vVTSRXnqcJfT05rmqThZ062ttaL23xmBpVzTw6o=";
    };
    flake = "true";
    date = "2025-07-11";
  };
  n8n = {
    pname = "n8n";
    version = "n8n@1.101.2";
    src = fetchurl {
      url = "https://github.com/n8n-io/n8n/archive/n8n@1.101.2.tar.gz";
      name = "n8n.tar.gz";
      sha256 = "sha256-sdMijJ+3n0JYNfZDNmLlL7I9Uyqk84NARsRxFw/+vzg=";
    };
  };
}
