# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aider = {
    pname = "aider";
    version = "v0.13.0";
    src = fetchFromGitHub {
      owner = "tninja";
      repo = "aider.el";
      rev = "v0.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-6TKklKxmgV4WNKjRN2vFhpti/oOskiaVLjwM3T8iHC8=";
    };
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "4778632b29c8c8d2b7cd9ce69535d0be01d846f9";
    src = fetchFromGitHub {
      owner = "domtronn";
      repo = "all-the-icons.el";
      rev = "4778632b29c8c8d2b7cd9ce69535d0be01d846f9";
      fetchSubmodules = false;
      sha256 = "sha256-3OhM+dEzAYDlvJL4bbvQMxherEwyC3wKC7Tjb168J6Q=";
    };
    date = "27 May 2025";
  };
  cape = {
    pname = "cape";
    version = "2.1";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "cape";
      rev = "2.1";
      fetchSubmodules = false;
      sha256 = "sha256-8BfMla3R8/q/ihId7PIOPv0iwkh/w3BgO1fPSqKYtEk=";
    };
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchFromGitHub {
      owner = "plexus";
      repo = "chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "20 Jan 2023";
  };
  color-rg = {
    pname = "color-rg";
    version = "41ad8fda5b6579a841889b2395c26cd642a006de";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "color-rg";
      rev = "41ad8fda5b6579a841889b2395c26cd642a006de";
      fetchSubmodules = false;
      sha256 = "sha256-wmFaEDvLNMM0Fk6g0eGBHTzqqOf1Qxne/yMc1rGTrZM=";
    };
    date = "07 Mar 2025";
  };
  color-theme-sanityinc-solarized = {
    pname = "color-theme-sanityinc-solarized";
    version = "f42431850e0ff0cff90c6cc39edc222faa40323d";
    src = fetchFromGitHub {
      owner = "purcell";
      repo = "color-theme-sanityinc-solarized";
      rev = "f42431850e0ff0cff90c6cc39edc222faa40323d";
      fetchSubmodules = false;
      sha256 = "sha256-CImGELoSOfvbGPQvl99jcCMksOmc4sGw//JIX5/K4pw=";
    };
    date = "26 Nov 2024";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "acea1487a5d47dce1fc75dc06abe18c7fd119f6e";
    src = fetchFromGitHub {
      owner = "zerolfx";
      repo = "copilot.el";
      rev = "acea1487a5d47dce1fc75dc06abe18c7fd119f6e";
      fetchSubmodules = false;
      sha256 = "sha256-oMOVku7u8P+u3MFljixgcJCl7OOp8y2OKjwAlTlysF0=";
    };
    date = "22 Jun 2025";
  };
  corfu = {
    pname = "corfu";
    version = "2.3";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "corfu";
      rev = "2.3";
      fetchSubmodules = false;
      sha256 = "sha256-+so01wEST4XXNu4cknPfr788SWx9UXNLc7E4cFL4ULg=";
    };
  };
  corfu-terminal = {
    pname = "corfu-terminal";
    version = "501548c3d51f926c687e8cd838c5865ec45d03cc";
    src = fetchgit {
      url = "https://codeberg.org/akib/emacs-corfu-terminal";
      rev = "501548c3d51f926c687e8cd838c5865ec45d03cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0qdSsuPE2s+DVu6yuqebMEt/29ypRlvb7TbvWEMHsjU=";
    };
    date = "10 Aug 2023";
  };
  dired-sidebar = {
    pname = "dired-sidebar";
    version = "3bc8927ed4d14a017eefc75d5af65022343e2ac1";
    src = fetchgit {
      url = "https://github.com/jojojames/dired-sidebar";
      rev = "3bc8927ed4d14a017eefc75d5af65022343e2ac1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5NZDHDKiiHzBMapEDv4rRGrKXY9VS9js5l28eaouvW0=";
    };
    description = "Sidebar for Emacs leveraging Dired";
    date = "12 Feb 2025";
  };
  gptel = {
    pname = "gptel";
    version = "v0.9.8.5";
    src = fetchFromGitHub {
      owner = "karthink";
      repo = "gptel";
      rev = "v0.9.8.5";
      fetchSubmodules = false;
      sha256 = "sha256-5/X4kuN3i7KeqSmdz0aetkiY+udFBxj5iquGtFuaoEc=";
    };
  };
  helm-sly = {
    pname = "helm-sly";
    version = "3691626c80620e992a338c3222283d9149f1ecb5";
    src = fetchFromGitHub {
      owner = "emacs-helm";
      repo = "helm-sly";
      rev = "3691626c80620e992a338c3222283d9149f1ecb5";
      fetchSubmodules = false;
      sha256 = "sha256-faIdZtWgDN6sz2/srTEZ+2sW/qNz0T2nVkeDHLrnqBs=";
    };
    date = "05 Feb 2021";
  };
  ibuffer-sidebar = {
    pname = "ibuffer-sidebar";
    version = "fb685e1e43db979e25713081d8ae4073453bbd5e";
    src = fetchgit {
      url = "https://github.com/jojojames/ibuffer-sidebar";
      rev = "fb685e1e43db979e25713081d8ae4073453bbd5e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ww4Npzgz/dnmGCU83WfcEyyTZYKjtoCdJdLv+uw7qBM=";
    };
    description = "A sidebar for IBuffer";
    date = "08 May 2021";
  };
  jinx = {
    pname = "jinx";
    version = "2.2";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "2.2";
      fetchSubmodules = false;
      sha256 = "sha256-/Q+GqsXMrLX0IxufK2iu74rtgEiiT2G7q9DuQeRvNrI=";
    };
  };
  lsp-mode = {
    pname = "lsp-mode";
    version = "8579c6c7771bc65564302e76296fb48855c558a4";
    src = fetchFromGitHub {
      owner = "emacs-lsp";
      repo = "lsp-mode";
      rev = "8579c6c7771bc65564302e76296fb48855c558a4";
      fetchSubmodules = false;
      sha256 = "sha256-V1qMao/eApZBC3Be0oIv2LqzWOV3Z+ceTFAlYx7B3p4=";
    };
    date = "24 Jun 2025";
  };
  maple-iedit = {
    pname = "maple-iedit";
    version = "2d0c819b767a6927bf3a256e9bf8c7dbf8570b9a";
    src = fetchFromGitHub {
      owner = "honmaple";
      repo = "emacs-maple-iedit";
      rev = "2d0c819b767a6927bf3a256e9bf8c7dbf8570b9a";
      fetchSubmodules = false;
      sha256 = "sha256-JEQiAQFEjYxlgyBQVWKiF9PmpaAlMEaqGeHWrrf0n58=";
    };
    description = "Emacs multiple cursors support based on iedit";
    date = "19 Sep 2024";
  };
  nerd-icons-corfu = {
    pname = "nerd-icons-corfu";
    version = "v0.5.1";
    src = fetchFromGitHub {
      owner = "LuigiPiucco";
      repo = "nerd-icons-corfu";
      rev = "v0.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-3CCdcb7zetHLQAxIpkiiWGx//oSuJGlJcOc8pSG8UUA=";
    };
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    date = "21 Apr 2023";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "62ce3a2dc39529c5db3516427e84b2c96b8efcfd";
    src = fetchgit {
      url = "https://github.com/nix-community/nix-ts-mode";
      rev = "62ce3a2dc39529c5db3516427e84b2c96b8efcfd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+TkkeiL2Dx8Tj5csLghQJFWlV3RqCHKDh2gEHX3hdZQ=";
    };
    date = "28 Feb 2025";
  };
  nixpkgs-fmt = {
    pname = "nixpkgs-fmt";
    version = "1f6fb42a5439589c44d99c661cc76958520323cc";
    src = fetchFromGitHub {
      owner = "purcell";
      repo = "emacs-nixpkgs-fmt";
      rev = "1f6fb42a5439589c44d99c661cc76958520323cc";
      fetchSubmodules = false;
      sha256 = "sha256-7Kxho74Av7FBvdlWXTD4dAw7Nl3pdY3j4C8MBq+vnTU=";
    };
    date = "06 Nov 2024";
  };
  orderless = {
    pname = "orderless";
    version = "1.4";
    src = fetchFromGitHub {
      owner = "oantolin";
      repo = "orderless";
      rev = "1.4";
      fetchSubmodules = false;
      sha256 = "sha256-iGpDDteSXzaWC++RTX4lhLVs1OlbWU4gAMYKMaYLSdE=";
    };
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchFromGitHub {
      owner = "Fuco1";
      repo = "org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "19 Mar 2023";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchFromGitHub {
      owner = "alphapapa";
      repo = "org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "05 Oct 2022";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "f40ece58df8b2f0fb6c8576b527755a552a5e763";
    src = fetchFromGitHub {
      owner = "Fanael";
      repo = "rainbow-delimiters";
      rev = "f40ece58df8b2f0fb6c8576b527755a552a5e763";
      fetchSubmodules = false;
      sha256 = "sha256-JcNRW0+L65NtOBronwyT7SHP9QsNa3ysj4cHv88yfoI=";
    };
    description = "Emacs rainbow delimiters mode";
    date = "30 Aug 2023";
  };
  sly = {
    pname = "sly";
    version = "63131ef965d8ff3a6b79cc7aff8e8f5fc1a82aec";
    src = fetchFromGitHub {
      owner = "joaotavora";
      repo = "sly";
      rev = "63131ef965d8ff3a6b79cc7aff8e8f5fc1a82aec";
      fetchSubmodules = false;
      sha256 = "sha256-C2MBBcNsmvI9xhY/gy2ongV9vulIacKeMxYAtsWwhJw=";
    };
    date = "23 May 2025";
  };
  sly-asdf = {
    pname = "sly-asdf";
    version = "6f9d751469bb82530db1673c22e7437ca6c95f45";
    src = fetchFromGitHub {
      owner = "mmgeorge";
      repo = "sly-asdf";
      rev = "6f9d751469bb82530db1673c22e7437ca6c95f45";
      fetchSubmodules = false;
      sha256 = "sha256-IKAqgByGd+HYcuTxscndvbQjP7Jn3jWy0w13ESCwqi8=";
    };
    date = "19 Nov 2022";
  };
  sly-macrostep = {
    pname = "sly-macrostep";
    version = "5113e4e926cd752b1d0bcc1508b3ebad5def5fad";
    src = fetchFromGitHub {
      owner = "joaotavora";
      repo = "sly-macrostep";
      rev = "5113e4e926cd752b1d0bcc1508b3ebad5def5fad";
      fetchSubmodules = false;
      sha256 = "sha256-GVDlwWUIT/IiTPqDQ3w54Tsz6NNl2bMtB3Y4Yh8Srts=";
    };
    date = "11 Dec 2019";
  };
  sly-named-readtables = {
    pname = "sly-named-readtables";
    version = "a5a42674ccffa97ccd5e4e9742beaf3ea719931f";
    src = fetchFromGitHub {
      owner = "joaotavora";
      repo = "sly-named-readtables";
      rev = "a5a42674ccffa97ccd5e4e9742beaf3ea719931f";
      fetchSubmodules = false;
      sha256 = "sha256-mJTXfxrYN3nWxv+/XqwqXiIdZ/YGC30poxn/nEJoWpk=";
    };
    date = "13 Oct 2019";
  };
  sly-overlay = {
    pname = "sly-overlay";
    version = "d62945059035f8097a6f222ed2700cfd99609d11";
    src = fetchFromGitHub {
      owner = "fosskers";
      repo = "sly-overlay";
      rev = "d62945059035f8097a6f222ed2700cfd99609d11";
      fetchSubmodules = false;
      sha256 = "sha256-ZfkZJkpVtJmseGwqrhLSF3XtK1q3s3JXVCZ+2MeGgaM=";
    };
    date = "28 Aug 2024";
  };
  sly-quicklisp = {
    pname = "sly-quicklisp";
    version = "34c73d43dd9066262387c626c17a9b486db07b2d";
    src = fetchFromGitHub {
      owner = "joaotavora";
      repo = "sly-quicklisp";
      rev = "34c73d43dd9066262387c626c17a9b486db07b2d";
      fetchSubmodules = false;
      sha256 = "sha256-YIP4yIuYFPXTs3GODcJuf9txDen0LX/3Ouvf9TTTEo8=";
    };
    date = "06 Dec 2021";
  };
  sly-repl-ansi-color = {
    pname = "sly-repl-ansi-color";
    version = "b9cd52d1cf927bf7e08582d46ab0bcf1d4fb5048";
    src = fetchFromGitHub {
      owner = "PuercoPop";
      repo = "sly-repl-ansi-color";
      rev = "b9cd52d1cf927bf7e08582d46ab0bcf1d4fb5048";
      fetchSubmodules = false;
      sha256 = "sha256-HfQu+2THLKMhEJLcSfDdL6uoDYpuHqC+9B79x5ex7Dk=";
    };
    date = "20 Oct 2017";
  };
  tempel = {
    pname = "tempel";
    version = "1.5";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "tempel";
      rev = "1.5";
      fetchSubmodules = false;
      sha256 = "sha256-fVZ7J/YgVM7HZXslP6jGDQ7Xazb5jW90h2bSh5uLnIA=";
    };
  };
  vertico = {
    pname = "vertico";
    version = "2.4";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "vertico";
      rev = "2.4";
      fetchSubmodules = false;
      sha256 = "sha256-Psxywo9xH+Rk3S7h2Xlircauxb0VFuFoBxpvNbp9NiE=";
    };
  };
  zetteldeft = {
    pname = "zetteldeft";
    version = "d2ddb3dc89d79c84fb8abd48478f7afe037d3a09";
    src = fetchFromGitHub {
      owner = "EFLS";
      repo = "zetteldeft";
      rev = "d2ddb3dc89d79c84fb8abd48478f7afe037d3a09";
      fetchSubmodules = false;
      sha256 = "sha256-eUwwZsVTNY1ZjIqk/5grpWjhLhy3aNKBD/2kAkQOSzQ=";
    };
    date = "17 Mar 2023";
  };
}
