# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Hyprspace = {
    pname = "Hyprspace";
    version = "0467be86b18cfc324fab04afbd40fe9ef80f7fa9";
    src = fetchgit {
      url = "https://github.com/KZDKM/Hyprspace";
      rev = "0467be86b18cfc324fab04afbd40fe9ef80f7fa9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IMa4mvkF0w7OAy+yEzPFYs2an332K30lf5qfUOAS9Cw=";
    };
    flake = "true";
    date = "2025-12-03";
  };
  contrib = {
    pname = "contrib";
    version = "41dbcac8183bb1b3a4ade0d8276b2f2df6ae4690";
    src = fetchgit {
      url = "https://github.com/hyprwm/contrib";
      rev = "41dbcac8183bb1b3a4ade0d8276b2f2df6ae4690";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-d3HmUbmfTDIt9mXEHszqyo2byqQMoyJtUJCZ9U1IqHQ=";
    };
    flake = "true";
    date = "2025-12-18";
  };
  grim-hyprland = {
    pname = "grim-hyprland";
    version = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
    src = fetchgit {
      url = "https://github.com/eriedaberrie/grim-hyprland";
      rev = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4m2QFT8mY6CM3YSebMJhd/kJWaRxTYOS/nvAs2TaIQs=";
    };
    flake = "true";
    date = "2025-03-11";
  };
  hy3 = {
    pname = "hy3";
    version = "hl0.52.0";
    src = fetchFromGitHub {
      owner = "outfoxxed";
      repo = "hy3";
      rev = "hl0.52.0";
      fetchSubmodules = false;
      sha256 = "sha256-UeMEUlQsil5DEtF/VQ//41vXJF9ff2xjoYVjhR6dqu4=";
    };
    flake = "true";
  };
  hypridle = {
    pname = "hypridle";
    version = "v0.1.7";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hypridle";
      rev = "v0.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-YzRWE3rCnsY0WDRJcn4KvyWUoe+5zdkUYNIaHGP9BZ4=";
    };
    flake = "true";
  };
  hyprland-plugins = {
    pname = "hyprland-plugins";
    version = "v0.53.0";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprland-plugins";
      rev = "v0.53.0";
      fetchSubmodules = false;
      sha256 = "sha256-BSRT1Uu1ot4WfMfZc6KW0nwpmt2xl9wpUqmH/JoMTfk=";
    };
    flake = "true";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-ucJ5C83hJy8XFO8Y+PL9hVcwdrQnj63BjXcO5A4qyNU=";
    };
    flake = "true";
  };
  hyprpicker = {
    pname = "hyprpicker";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprpicker";
      rev = "v0.4.5";
      fetchSubmodules = true;
      sha256 = "sha256-ta3eCdXyKTVKhCU2/zC+XljU1Tq5huIyuFBtzOcUU4c=";
    };
    flake = "true";
  };
  hyprsunset = {
    pname = "hyprsunset";
    version = "v0.3.3";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsunset";
      rev = "v0.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-Yk6nDzCXrOehX3At8qdZ0cLr1kPySqACsihMYuP6T8w=";
    };
    flake = "true";
  };
  hyprsysteminfo = {
    pname = "hyprsysteminfo";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsysteminfo";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-KDxT9B+1SATWiZdUBAQvZu17vk3xmyXcw2Zy56bdWbY=";
    };
    flake = "true";
  };
  pyprland = {
    pname = "pyprland";
    version = "2.5.1";
    src = fetchFromGitHub {
      owner = "hyprland-community";
      repo = "pyprland";
      rev = "2.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-f3FhkR2asMKK7kckXMWl8Un0hd7A3hZtsviZrBTqzEo=";
    };
    flake = "true";
  };
  waybar = {
    pname = "waybar";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "Alexays";
      repo = "Waybar";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-mGiBZjfvtZZkSHrha4UF2l1Ogbij8J//r2h4gcZAJ6w=";
    };
    flake = "true";
  };
}
