# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Hyprspace = {
    pname = "Hyprspace";
    version = "847a770436e1ecebdbe5ed006a93db7666937ff2";
    src = fetchgit {
      url = "https://github.com/KZDKM/Hyprspace";
      rev = "847a770436e1ecebdbe5ed006a93db7666937ff2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-493llKN7yyLkKlz8uYVAyvXH261IpDzuVA+TnewFIAg=";
    };
    flake = "true";
    date = "2025-06-30";
  };
  contrib = {
    pname = "contrib";
    version = "34d0c01910552b873a07c96921ef70e32bf369a2";
    src = fetchgit {
      url = "https://github.com/hyprwm/contrib";
      rev = "34d0c01910552b873a07c96921ef70e32bf369a2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dyzDJvt8IVgHJVmpnw1mueHHSLYnChW1XMkwz9WUBZ8=";
    };
    flake = "true";
    date = "2025-07-09";
  };
  grim-hyprland = {
    pname = "grim-hyprland";
    version = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
    src = fetchgit {
      url = "https://github.com/eriedaberrie/grim-hyprland";
      rev = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4m2QFT8mY6CM3YSebMJhd/kJWaRxTYOS/nvAs2TaIQs=";
    };
    flake = "true";
    date = "2025-03-11";
  };
  hy3 = {
    pname = "hy3";
    version = "hl0.49.0";
    src = fetchFromGitHub {
      owner = "outfoxxed";
      repo = "hy3";
      rev = "hl0.49.0";
      fetchSubmodules = false;
      sha256 = "sha256-dYxkdbg6yj8HhuBkCmklMQVR17N7P32R8ir7b7oNxm4=";
    };
    flake = "true";
  };
  hypridle = {
    pname = "hypridle";
    version = "v0.1.6";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hypridle";
      rev = "v0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-uChAGmceKS9F9jqs1xb58BLTVZLF+sFU00MWDEVfYLg=";
    };
    flake = "true";
  };
  hyprland-plugins = {
    pname = "hyprland-plugins";
    version = "v0.49.0";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprland-plugins";
      rev = "v0.49.0";
      fetchSubmodules = false;
      sha256 = "sha256-GpsLyK/U05q7QnyFIWrnGS2loVyjPZByTtPitwu9UNw=";
    };
    flake = "true";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "v0.8.2";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "v0.8.2";
      fetchSubmodules = false;
      sha256 = "sha256-9amK5DEpueAD+aobmBmjbV+C16RO7lcDOdf5ucJtNvM=";
    };
    flake = "true";
  };
  hyprpicker = {
    pname = "hyprpicker";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprpicker";
      rev = "v0.4.5";
      fetchSubmodules = true;
      sha256 = "sha256-ta3eCdXyKTVKhCU2/zC+XljU1Tq5huIyuFBtzOcUU4c=";
    };
    flake = "true";
  };
  hyprsunset = {
    pname = "hyprsunset";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsunset";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-EIJka3UtSEtmkDBjYiGeR/hO6s6R4x3K+rbUlc9KPBE=";
    };
    flake = "true";
  };
  hyprsysteminfo = {
    pname = "hyprsysteminfo";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsysteminfo";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-KDxT9B+1SATWiZdUBAQvZu17vk3xmyXcw2Zy56bdWbY=";
    };
    flake = "true";
  };
  pyprland = {
    pname = "pyprland";
    version = "2.4.6";
    src = fetchFromGitHub {
      owner = "hyprland-community";
      repo = "pyprland";
      rev = "2.4.6";
      fetchSubmodules = false;
      sha256 = "sha256-OH+BTPw574FykVYWG6TIOpSPeYB39UxyMy/gzMDw0z4=";
    };
    flake = "true";
  };
  waybar = {
    pname = "waybar";
    version = "0.13.0";
    src = fetchFromGitHub {
      owner = "Alexays";
      repo = "Waybar";
      rev = "0.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-KfWjYDqJf2jNmYAnmV7EQHweMObEBreUc2G7/LpvvC0=";
    };
    flake = "true";
  };
}
