# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  Hyprspace = {
    pname = "Hyprspace";
    version = "2b61fd2115262243b03aa9afe8dfd8a78e71636c";
    src = fetchgit {
      url = "https://github.com/KZDKM/Hyprspace";
      rev = "2b61fd2115262243b03aa9afe8dfd8a78e71636c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-npC+H+Wl60EdrV75sjqm+bbbLbKgCCGn4ALSM0B2OWA=";
    };
    flake = "true";
    date = "2025-08-11";
  };
  contrib = {
    pname = "contrib";
    version = "6839b23345b71db17cd408373de4f5605bf589b8";
    src = fetchgit {
      url = "https://github.com/hyprwm/contrib";
      rev = "6839b23345b71db17cd408373de4f5605bf589b8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PFAJoEqQWMlo1J+yZb+4HixmhbRVmmNl58e/AkLYDDI=";
    };
    flake = "true";
    date = "2025-07-23";
  };
  grim-hyprland = {
    pname = "grim-hyprland";
    version = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
    src = fetchgit {
      url = "https://github.com/eriedaberrie/grim-hyprland";
      rev = "4a3d6f5b87b01e92c404b9393b79057b85f58c60";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4m2QFT8mY6CM3YSebMJhd/kJWaRxTYOS/nvAs2TaIQs=";
    };
    flake = "true";
    date = "2025-03-11";
  };
  hy3 = {
    pname = "hy3";
    version = "hl0.50.0";
    src = fetchFromGitHub {
      owner = "outfoxxed";
      repo = "hy3";
      rev = "hl0.50.0";
      fetchSubmodules = false;
      sha256 = "sha256-1BTJSqkj+lkIry27HuqA5UB7uRqAUvGT7LAUDQhKjU0=";
    };
    flake = "true";
  };
  hypridle = {
    pname = "hypridle";
    version = "v0.1.6";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hypridle";
      rev = "v0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-uChAGmceKS9F9jqs1xb58BLTVZLF+sFU00MWDEVfYLg=";
    };
    flake = "true";
  };
  hyprland-plugins = {
    pname = "hyprland-plugins";
    version = "v0.50.0";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprland-plugins";
      rev = "v0.50.0";
      fetchSubmodules = false;
      sha256 = "sha256-XJJ+frO4NOxVkoSGc1Mag8ESumzx2FmVRspOgFlMqF8=";
    };
    flake = "true";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-hHTJ65uOiGqQgI2XbH9jqIGHUcA86K+GJbnhAKhRWNo=";
    };
    flake = "true";
  };
  hyprpicker = {
    pname = "hyprpicker";
    version = "v0.4.5";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprpicker";
      rev = "v0.4.5";
      fetchSubmodules = true;
      sha256 = "sha256-ta3eCdXyKTVKhCU2/zC+XljU1Tq5huIyuFBtzOcUU4c=";
    };
    flake = "true";
  };
  hyprsunset = {
    pname = "hyprsunset";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsunset";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-eYLtZJayWWbKBC3u/gvDSqVyffuD+egryr7zPWRAeyY=";
    };
    flake = "true";
  };
  hyprsysteminfo = {
    pname = "hyprsysteminfo";
    version = "v0.1.3";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprsysteminfo";
      rev = "v0.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-KDxT9B+1SATWiZdUBAQvZu17vk3xmyXcw2Zy56bdWbY=";
    };
    flake = "true";
  };
  pyprland = {
    pname = "pyprland";
    version = "2.4.7";
    src = fetchFromGitHub {
      owner = "hyprland-community";
      repo = "pyprland";
      rev = "2.4.7";
      fetchSubmodules = false;
      sha256 = "sha256-rtAw6tdZY0BKb6Qjk/LHYYMB9nCPzkmw95wdjhJ191s=";
    };
    flake = "true";
  };
  waybar = {
    pname = "waybar";
    version = "0.14.0";
    src = fetchFromGitHub {
      owner = "Alexays";
      repo = "Waybar";
      rev = "0.14.0";
      fetchSubmodules = false;
      sha256 = "sha256-mGiBZjfvtZZkSHrha4UF2l1Ogbij8J//r2h4gcZAJ6w=";
    };
    flake = "true";
  };
}
