### NOTE: https://github.com/hyprland-community/awesome-hyprland

[hy3]
src.use_latest_tag = true
src.github_tag = "outfoxxed/hy3"
fetch.github = "outfoxxed/hy3"
passthru = { flake = "true" }

[hyprlock]
src.use_latest_tag = true
src.github_tag = "hyprwm/hyprlock"
fetch.github = "hyprwm/hyprlock"
passthru = { flake = "true" }

[hypridle]
src.use_latest_tag = true
src.github_tag = "hyprwm/hypridle"
fetch.github = "hyprwm/hypridle"
passthru = { flake = "true" }

[hyprland-plugins]
src.use_latest_tag = true
src.github_tag = "hyprwm/hyprland-plugins"
fetch.github = "hyprwm/hyprland-plugins"
passthru = { flake = "true" }

[hyprpicker]
src.use_latest_tag = true
src.github_tag = "hyprwm/hyprpicker"
fetch.github = "hyprwm/hyprpicker"
git.fetchSubmodules = true
passthru = { flake = "true" }

[hyprsunset]
src.use_latest_tag = true
src.github_tag = "hyprwm/hyprsunset"
fetch.github = "hyprwm/hyprsunset"
passthru = { flake = "true" }

[hyprsysteminfo]
src.use_latest_tag = true
src.github_tag = "hyprwm/hyprsysteminfo"
fetch.github = "hyprwm/hyprsysteminfo"
passthru = { flake = "true" }

[contrib]
src.git = "https://github.com/hyprwm/contrib"
fetch.git = "https://github.com/hyprwm/contrib"
passthru = { flake = "true" }

[pyprland]
src.use_latest_tag = true
src.github_tag = "hyprland-community/pyprland"
fetch.github = "hyprland-community/pyprland"
passthru = { flake = "true" }

[grim-hyprland]
src.git = "https://github.com/eriedaberrie/grim-hyprland"
fetch.git = "https://github.com/eriedaberrie/grim-hyprland"
passthru = { flake = "true" }

[Hyprspace]
src.git = "https://github.com/KZDKM/Hyprspace"
fetch.git = "https://github.com/KZDKM/Hyprspace"
passthru = { flake = "true" }

# https://github.com/VirtCode/hypr-dynamic-cursors

###
[waybar]
src.use_latest_tag = true
src.github_tag = "Alexays/Waybar"
fetch.github = "Alexays/Waybar"
passthru = { flake = "true" }
