# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acl-compat = {
    pname = "acl-compat";
    version = "cac1d6920998ddcbee8310a873414732e707d8e5";
    src = fetchgit {
      url = "https://git.code.sf.net/p/portableaserve/git";
      rev = "cac1d6920998ddcbee8310a873414732e707d8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CvfiudyBNYQsyPFy05kjbhGVtwl56wKPAllqgi6uZio=";
    };
    date = "2019-07-20";
  };
  adguard-filters = {
    pname = "adguard-filters";
    version = "aab62f03f302e0e0c11079fc45814e1057f44e9f";
    src = fetchgit {
      url = "https://github.com/AdguardTeam/AdguardFilters";
      rev = "aab62f03f302e0e0c11079fc45814e1057f44e9f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hhrgOHtUbosx7tkUrs3ZmtQjqx5bJzP2c6U5YYcmiT8=";
    };
    date = "2024-07-12";
  };
  age-plugin-trezor = {
    pname = "age-plugin-trezor";
    version = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "age-plugin-trezor";
      rev = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2021-01-01";
  };
  base16-schemes = {
    pname = "base16-schemes";
    version = "ef9a4c3c384624694608adebf0993d7a3bed3cf2";
    src = fetchgit {
      url = "https://github.com/tinted-theming/schemes";
      rev = "ef9a4c3c384624694608adebf0993d7a3bed3cf2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9i9IjZcjvinb/214x5YShUDBZBC2189HYs26uGy/Hck=";
    };
    date = "2024-06-21";
  };
  chatgpt-wrapper = {
    pname = "chatgpt-wrapper";
    version = "7c5b79fecf5ad7ab6f286c286ba6782f84fe0459";
    src = fetchFromGitHub {
      owner = "llm-workflow-engine";
      repo = "llm-workflow-engine";
      rev = "7c5b79fecf5ad7ab6f286c286ba6782f84fe0459";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2024-07-09";
  };
  cl-hash-util = {
    pname = "cl-hash-util";
    version = "7f88cb7579b2af8c21022554f46dddd6ce6a5fc2";
    src = fetchFromGitHub {
      owner = "orthecreedence";
      repo = "cl-hash-util";
      rev = "7f88cb7579b2af8c21022554f46dddd6ce6a5fc2";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2024-06-17";
  };
  cl-mount-info = {
    pname = "cl-mount-info";
    version = "5a7fbdbfe4ac3810c7f00434d3d6dc7555891705";
    src = fetchgit {
      url = "https://codeberg.org/cage/cl-mount-info";
      rev = "5a7fbdbfe4ac3810c7f00434d3d6dc7555891705";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nFEecXmStgu/ePtNretaCgC1huBr4kKnzvgdoUG+u0Q=";
    };
    date = "2023-06-20";
  };
  cl-shellwords = {
    pname = "cl-shellwords";
    version = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
    src = fetchFromGitHub {
      owner = "jorams";
      repo = "cl-shellwords";
      rev = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2015-09-20";
  };
  cl-strings = {
    pname = "cl-strings";
    version = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
    src = fetchFromGitHub {
      owner = "diogoalexandrefranco";
      repo = "cl-strings";
      rev = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2021-03-08";
  };
  cl-syslog = {
    pname = "cl-syslog";
    version = "f62d524874616383650e30f7f23320005fd310c1";
    src = fetchFromGitHub {
      owner = "lhope";
      repo = "cl-syslog";
      rev = "f62d524874616383650e30f7f23320005fd310c1";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2006-11-28";
  };
  console-solarized = {
    pname = "console-solarized";
    version = "26929b5e303703ec527b6f6e4569f351d9831e52";
    src = fetchFromGitHub {
      owner = "adeverteuil";
      repo = "console-solarized";
      rev = "26929b5e303703ec527b6f6e4569f351d9831e52";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2018-10-28";
  };
  crystalline = {
    pname = "crystalline";
    version = "v0.13.1";
    src = fetchFromGitHub {
      owner = "elbywan";
      repo = "crystalline";
      rev = "v0.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  dbus = {
    pname = "dbus";
    version = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
    src = fetchgit {
      url = "https://github.com/death/dbus";
      rev = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xbg3tPYfRNGJo+9F/58w2bDeZqV33Z871+ClSg4ACPk=";
    };
    date = "2023-11-04";
  };
  dbus-listen = {
    pname = "dbus-listen";
    version = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
    src = fetchgit {
      url = "https://github.com/voobscout/dbus-listen";
      rev = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WU3e7F0iNrxiS7WXzNbxnBp4oIru2pLihKbVIR236J4=";
    };
    date = "2022-09-09";
  };
  firefox_decrypt = {
    pname = "firefox_decrypt";
    version = "1.1.1";
    src = fetchFromGitHub {
      owner = "unode";
      repo = "firefox_decrypt";
      rev = "1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  firefox_user_js = {
    pname = "firefox_user_js";
    version = "126.1";
    src = fetchFromGitHub {
      owner = "arkenfox";
      repo = "user.js";
      rev = "126.1";
      fetchSubmodules = false;
      sha256 = "sha256-Ex+eSb7tZ428MMJDIF/nqUOtnzjqEIPNaDXJPm9FvuY=";
    };
  };
  git-get = {
    pname = "git-get";
    version = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
    src = fetchFromGitHub {
      owner = "grdl";
      repo = "git-get";
      rev = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    vendorHash = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b";
    date = "2021-08-07";
  };
  git-pull-request-mirror = {
    pname = "git-pull-request-mirror";
    version = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
    src = fetchFromGitHub {
      owner = "google";
      repo = "git-pull-request-mirror";
      rev = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn";
    date = "2020-05-13";
  };
  git-remote-ipfs = {
    pname = "git-remote-ipfs";
    version = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
    src = fetchFromGitHub {
      owner = "bqv";
      repo = "git-remote-ipfs";
      rev = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=";
    date = "2021-01-24";
  };
  ipxe = {
    pname = "ipxe";
    version = "5a9f476d4f1395e69cbb845d7379b0e3591028c0";
    src = fetchgit {
      url = "https://github.com/ipxe/ipxe";
      rev = "5a9f476d4f1395e69cbb845d7379b0e3591028c0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-I9Dsze42sg4EhK8/QdQ2XDpWrbfCYVdQDkmHJ75r5mM=";
    };
    date = "2024-07-08";
  };
  iterable-io = {
    pname = "iterable-io";
    version = "1.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/i/iterable-io/iterable-io-1.0.0.tar.gz";
      sha256 = "sha256-+54bc5WHqboNXGCj4etxJGdhWDvJ8Ys8NbsRK0SxjDw=";
    };
  };
  langchain = {
    pname = "langchain";
    version = "langchain-core==0.2.16";
    src = fetchFromGitHub {
      owner = "langchain-ai";
      repo = "langchain";
      rev = "langchain-core==0.2.16";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  ledger-live-desktop = {
    pname = "ledger-live-desktop";
    version = "2.77.2";
    src = fetchurl {
      url = "https://download.live.ledger.com/ledger-live-desktop-2.77.2-linux-x86_64.AppImage";
      sha256 = "sha256-orIyfRs6TJgqGGLpl2tvoUtejsB0ni8xRK0SboP2LHw=";
    };
  };
  listopia = {
    pname = "listopia";
    version = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
    src = fetchFromGitHub {
      owner = "Dimercel";
      repo = "listopia";
      rev = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2021-03-17";
  };
  logseq = {
    pname = "logseq";
    version = "0.10.9";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.10.9/logseq-linux-x64-0.10.9.AppImage";
      sha256 = "sha256-XROuY2RlKnGvK1VNvzauHuLJiveXVKrIYPppoz8fCmc=";
    };
  };
  masterpdfeditor = {
    pname = "masterpdfeditor";
    version = "5.9.82";
    src = fetchurl {
      url = "https://code-industry.net/public/master-pdf-editor-5.9.82-qt5.x86_64.tar.gz";
      sha256 = "sha256-CbrhhQJ0iiXz8hUJEi+/xb2ZGbunuPuIIgmCRgJhNVU=";
    };
  };
  numix-solarized-gtk-theme-git = {
    pname = "numix-solarized-gtk-theme-git";
    version = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
    src = fetchgit {
      url = "https://github.com/Ferdi265/numix-solarized-gtk-theme";
      rev = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-r5xCe8Ew+/SuCUaZ0yjlumORTy/y1VwbQQjQ6uEyGsY=";
    };
    date = "2023-03-05";
  };
  pam_usb = {
    pname = "pam_usb";
    version = "a2d14f844d16dc242a46fcae50b77dd83daa86cd";
    src = fetchgit {
      url = "https://github.com/mcdope/pam_usb";
      rev = "a2d14f844d16dc242a46fcae50b77dd83daa86cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oWamrnH8xXXyGIbWgNC4l5/n9KZUOUtttrpafNn9R30=";
    };
    date = "2024-07-08";
  };
  paper-store = {
    pname = "paper-store";
    version = "f369e81f8723123d89b8ac527f955e4d4c60b7fd";
    src = fetchgit {
      url = "https://github.com/nurupo/paper-store";
      rev = "f369e81f8723123d89b8ac527f955e4d4c60b7fd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-StmpmszWHzmi8pMd+y3f6+1s2vjW8HM5O6maJiE6Ajc=";
    };
    date = "2024-04-06";
  };
  pbkdf2-sha512 = {
    pname = "pbkdf2-sha512";
    version = "b521675c515be29b61d78194db97563c380a7574";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c";
      sha256 = "sha256-OelyIsDDto6Ir22YY/UM+r9EBx6K8TNdjM3efzUJxE8=";
    };
    date = "2024-07-12";
  };
  pgp-key-generation = {
    pname = "pgp-key-generation";
    version = "e4549972b1ed686b38da9e2a663106669edddb9b";
    src = fetchFromGitHub {
      owner = "summitto";
      repo = "pgp-key-generation";
      rev = "e4549972b1ed686b38da9e2a663106669edddb9b";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2022-12-02";
  };
  pgp-packet-library = {
    pname = "pgp-packet-library";
    version = "42b4d08c0cb4b8ee527f729c1674e982eca409a7";
    src = fetchFromGitHub {
      owner = "summitto";
      repo = "pgp-packet-library";
      rev = "42b4d08c0cb4b8ee527f729c1674e982eca409a7";
      fetchSubmodules = true;
      sha256 = "sha256-DI0vxfbewqlXocrvzPgCM66IuSVxHjFdL3hIPxzFou8=";
    };
    date = "2022-07-26";
  };
  python-pass = {
    pname = "python-pass";
    version = "6f51145a3bc12ee79d2881204b88a82d149f3228";
    src = fetchFromGitHub {
      owner = "aviau";
      repo = "python-pass";
      rev = "6f51145a3bc12ee79d2881204b88a82d149f3228";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  quicklisp = {
    pname = "quicklisp";
    version = "latest";
    src = fetchurl {
      url = "https://beta.quicklisp.org/quicklisp.lisp";
      sha256 = "sha256-SnpcKuvgcWQXBHhUJnOX4kpE0MzglhJ0EenOnM/rLBc=";
    };
  };
  s5cmd = {
    pname = "s5cmd";
    version = "787bc8805d8a639ca83fb64eda0521d0d43869d8";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "787bc8805d8a639ca83fb64eda0521d0d43869d8";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2024-07-12";
  };
  solarized-dark-gnome-shell-2020 = {
    pname = "solarized-dark-gnome-shell-2020";
    version = "fa0ce0fe63ae314938e11843074fe0955f89e9ac";
    src = fetchgit {
      url = "https://github.com/rtlewis88/rtl88-Themes";
      rev = "fa0ce0fe63ae314938e11843074fe0955f89e9ac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Rtaf0LRcWJ/a3yTFPMSPk6vlK0UW6dyStnAVJ24jREg=";
    };
    date = "2020-10-20";
  };
  solarized-darkarc = {
    pname = "solarized-darkarc";
    version = "ab0a4d325b6c3bc34293850abcacc924b2ee2933";
    src = fetchgit {
      url = "https://github.com/rtlewis1/GTK";
      rev = "ab0a4d325b6c3bc34293850abcacc924b2ee2933";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rBNlEgMyjPqt/e68pYery+puBAbiy0CskBjeKx0Tq/0=";
    };
    date = "2023-11-19";
  };
  solarized-material = {
    pname = "solarized-material";
    version = "93ab6a4b7683795ee9da42f39c1ad28a23ac8b3c";
    src = fetchgit {
      url = "https://github.com/rtlewis1/GTK";
      rev = "93ab6a4b7683795ee9da42f39c1ad28a23ac8b3c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MDAewKv1DRoCxWfSCj6+EEtkFFYjm9z5iPZQ3xCjpqM=";
    };
    date = "2023-11-26";
  };
  solarized-sddm = {
    pname = "solarized-sddm";
    version = "2b5bdf1045f2a5c8b880b482840be8983ca06191";
    src = fetchgit {
      url = "https://github.com/MalditoBarbudo/solarized_sddm_theme";
      rev = "2b5bdf1045f2a5c8b880b482840be8983ca06191";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uVNYmpPM2o9Fq3A1gP04ffXeWdc7y2HP1g7vkiuJZtg=";
    };
    date = "2019-01-03";
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "042a9fcb053839f4b1527d2e6f4baf33e2d16434";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm-contrib";
      rev = "042a9fcb053839f4b1527d2e6f4baf33e2d16434";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2024-04-18";
  };
  stumpwm-git = {
    pname = "stumpwm-git";
    version = "11be454df8f01f2ed7aa20cffe23f16f1d7b7bd6";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "11be454df8f01f2ed7aa20cffe23f16f1d7b7bd6";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    system = "stumpwm";
    asd = "stumpwm";
    date = "2024-04-18";
  };
  stumpwm-release = {
    pname = "stumpwm-release";
    version = "23.11";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "23.11";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    system = "stumpwm";
    asd = "stumpwm";
  };
  sublimeSolarized = {
    pname = "sublimeSolarized";
    version = "2.7.5";
    src = fetchFromGitHub {
      owner = "braver";
      repo = "Solarized";
      rev = "2.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  tfenv = {
    pname = "tfenv";
    version = "39d8c27ad9862ffdec57989b66fd2720cb72e76c";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "39d8c27ad9862ffdec57989b66fd2720cb72e76c";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
    date = "2023-12-19";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
  trezor-agent = {
    pname = "trezor-agent";
    version = "v0.14.8";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "trezor-agent";
      rev = "v0.14.8";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
  trezor-agent-subkeys = {
    pname = "trezor-agent-subkeys";
    version = "eac2f8215f2c11a92faf30170277c57bb7289801";
    src = fetchgit {
      url = "https://github.com/jrruethe/trezor-agent";
      rev = "eac2f8215f2c11a92faf30170277c57bb7289801";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DA5REsNQNykpbCFb6PJbgEBYiDh1kEq083wRZq+pIQM=";
    };
    date = "2023-06-09";
  };
  trezor-gpg-pinentry-tk = {
    pname = "trezor-gpg-pinentry-tk";
    version = "0.0.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/trezor-gpg-pinentry-tk/trezor-gpg-pinentry-tk-0.0.10.tar.gz";
      sha256 = "sha256-h/NJKbKBP5Sbq0BYJes1h2ka2/k2gSUr564qOQZeAc4=";
    };
  };
  waveterm = {
    pname = "waveterm";
    version = "v0.7.6";
    src = fetchFromGitHub {
      owner = "wavetermdev";
      repo = "waveterm";
      rev = "v0.7.6";
      fetchSubmodules = false;
      sha256 = "sha256-5LDxnQQq2gvovlMbgKyTS5D51AYUQrlA4RKvjKOLnSw=";
    };
  };
}
