# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.4.20231102";
    src = fetchurl {
      url = "https://pypi.org/packages/source/H/HPI/HPI-0.4.20231102.tar.gz";
      sha256 = "sha256-V3lzJs17I3zwaDowngD0gr1t0zRlMnuE7QZeb4dlbXA=";
    };
  };
  acl-compat = {
    pname = "acl-compat";
    version = "cac1d6920998ddcbee8310a873414732e707d8e5";
    src = fetchgit {
      url = "https://git.code.sf.net/p/portableaserve/git";
      rev = "cac1d6920998ddcbee8310a873414732e707d8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CvfiudyBNYQsyPFy05kjbhGVtwl56wKPAllqgi6uZio=";
    };
    date = "2019-07-20";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.41";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.41/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-nhcSAhA/9XvU3evCgMvHHrejP1sbojFw9GKz383Kk/U=";
    };
  };
  age-plugin-trezor = {
    pname = "age-plugin-trezor";
    version = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "age-plugin-trezor";
      rev = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
      fetchSubmodules = false;
      sha256 = "sha256-EXhbCjIl5xDfxOZIQEDWHSFnWabwlVC5EYWk4ezAXy8=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2021-01-01";
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
    src = fetchFromGitHub {
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
      fetchSubmodules = false;
      sha256 = "sha256-j1DE0WTBGLmBLoPmqST9YVj9Jc4Mp8WXQILmPBzRlbM=";
    };
    date = "2023-11-08";
  };
  chatgpt-wrapper = {
    pname = "chatgpt-wrapper";
    version = "d7ff94fdf96209c2f59d371c08340daf22d7ade9";
    src = fetchFromGitHub {
      owner = "mmabrouk";
      repo = "chatgpt-wrapper";
      rev = "d7ff94fdf96209c2f59d371c08340daf22d7ade9";
      fetchSubmodules = false;
      sha256 = "sha256-1tV/AmQ+wvYF+wrxC7WuJU9SB9JCWccWRL/2tbxIJYs=";
    };
    date = "2023-11-26";
  };
  cl-hash-util = {
    pname = "cl-hash-util";
    version = "43f6d363722bf849bef10010e07fca17f024fb9d";
    src = fetchFromGitHub {
      owner = "orthecreedence";
      repo = "cl-hash-util";
      rev = "43f6d363722bf849bef10010e07fca17f024fb9d";
      fetchSubmodules = false;
      sha256 = "sha256-A1pZT35RkA9xeQ7ulh2shrqEMUgSoYx8Ry3j1GyRWPU=";
    };
    date = "2023-07-05";
  };
  cl-shellwords = {
    pname = "cl-shellwords";
    version = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
    src = fetchFromGitHub {
      owner = "jorams";
      repo = "cl-shellwords";
      rev = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
      fetchSubmodules = false;
      sha256 = "sha256-9hKq54YOOEE3Vc/9LVUnqvcw/1G1rpcUVL+8GKJlqEY=";
    };
    date = "2015-09-20";
  };
  cl-strings = {
    pname = "cl-strings";
    version = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
    src = fetchFromGitHub {
      owner = "diogoalexandrefranco";
      repo = "cl-strings";
      rev = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
      fetchSubmodules = false;
      sha256 = "sha256-UpXjI9KsWvOhsjGSo1zVMNlD1I4Pwu9+cZoD60jREMk=";
    };
    date = "2021-03-08";
  };
  cl-syslog = {
    pname = "cl-syslog";
    version = "f62d524874616383650e30f7f23320005fd310c1";
    src = fetchFromGitHub {
      owner = "lhope";
      repo = "cl-syslog";
      rev = "f62d524874616383650e30f7f23320005fd310c1";
      fetchSubmodules = false;
      sha256 = "sha256-rH0zOgXR3BixtVaqcYPhIfZBjqYgWnqrORQfr1mBqFM=";
    };
    date = "2006-11-28";
  };
  console-solarized = {
    pname = "console-solarized";
    version = "26929b5e303703ec527b6f6e4569f351d9831e52";
    src = fetchFromGitHub {
      owner = "adeverteuil";
      repo = "console-solarized";
      rev = "26929b5e303703ec527b6f6e4569f351d9831e52";
      fetchSubmodules = false;
      sha256 = "sha256-QMxhuDuVHgw8+DpQAavtC3Dyg4rBmbrYoA8tKtamy3Y=";
    };
    date = "2018-10-28";
  };
  dbus = {
    pname = "dbus";
    version = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
    src = fetchgit {
      url = "https://github.com/death/dbus";
      rev = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xbg3tPYfRNGJo+9F/58w2bDeZqV33Z871+ClSg4ACPk=";
    };
    date = "2023-11-04";
  };
  dbus-listen = {
    pname = "dbus-listen";
    version = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
    src = fetchgit {
      url = "https://github.com/voobscout/dbus-listen";
      rev = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WU3e7F0iNrxiS7WXzNbxnBp4oIru2pLihKbVIR236J4=";
    };
    date = "2022-09-09";
  };
  drawio = {
    pname = "drawio";
    version = "22.1.2";
    src = fetchurl {
      url = "https://github.com/jgraph/drawio-desktop/releases/download/v22.1.2/drawio-x86_64-22.1.2.rpm";
      sha256 = "sha256-GXqk3adIj/8U1lq94TCBVX4tS44na4AVDj+M87UXws4=";
    };
  };
  getoptions = {
    pname = "getoptions";
    version = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
    src = fetchFromGitHub {
      owner = "ko1nksm";
      repo = "getoptions";
      rev = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
      fetchSubmodules = false;
      sha256 = "sha256-MJ4UUDmd+yykvRjgxx8MRZwlLNauDb8Bh8lS0QvkG+U=";
    };
    date = "2022-07-03";
  };
  git-get = {
    pname = "git-get";
    version = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
    src = fetchFromGitHub {
      owner = "grdl";
      repo = "git-get";
      rev = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
      fetchSubmodules = false;
      sha256 = "sha256-dBZNrhg4df7NDECq8B333dY/7OXEyPIByD7YHdV9moo=";
    };
    vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b";
    date = "2021-08-07";
  };
  git-pull-request-mirror = {
    pname = "git-pull-request-mirror";
    version = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
    src = fetchFromGitHub {
      owner = "google";
      repo = "git-pull-request-mirror";
      rev = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
      fetchSubmodules = false;
      sha256 = "sha256-OMtRSGRB1xRk3L3sIfEpagDQHNWNJBBOE5tuW7ic4Y4=";
    };
    vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn";
    date = "2020-05-13";
  };
  git-remote-ipfs = {
    pname = "git-remote-ipfs";
    version = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
    src = fetchFromGitHub {
      owner = "bqv";
      repo = "git-remote-ipfs";
      rev = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
      fetchSubmodules = false;
      sha256 = "sha256-59zv362KfuW1Lki9vfwe9fJfdm6o0+DTPDbI/L+Ugsk=";
    };
    vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=";
    date = "2021-01-24";
  };
  gpg-hd = {
    pname = "gpg-hd";
    version = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
    src = fetchFromGitHub {
      owner = "Logicwax";
      repo = "gpg-hd";
      rev = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
      fetchSubmodules = false;
      sha256 = "sha256-O78meAbNTFh2ZhgxCbuA85kChtiR+fZ/S5jfvcQuymg=";
    };
    date = "2023-02-22";
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  langchain = {
    pname = "langchain";
    version = "0.0.344";
    src = fetchurl {
      url = "https://pypi.org/packages/source/l/langchain/langchain-0.0.344.tar.gz";
      sha256 = "sha256-N6bXLSOu5U/B3+o5NO1jdi9gToZl/gCPt6MMRZH+gI0=";
    };
  };
  listopia = {
    pname = "listopia";
    version = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
    src = fetchFromGitHub {
      owner = "Dimercel";
      repo = "listopia";
      rev = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
      fetchSubmodules = false;
      sha256 = "sha256-IEoPmF0QC1S6xF/enlqy1rDX8qi/2bvacxWpCHaro0k=";
    };
    date = "2021-03-17";
  };
  logseq = {
    pname = "logseq";
    version = "0.10.0";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.10.0/logseq-linux-x64-0.10.0.AppImage";
      sha256 = "sha256-igZM+kNe1GDPYckXU6fOjyovHe9gwyBWr7Mc3BxAzOA=";
    };
  };
  lorri = {
    pname = "lorri";
    version = "30bb920dec9f3ca0bd0bc6cd60b78ca2f90c69a9";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "lorri";
      rev = "30bb920dec9f3ca0bd0bc6cd60b78ca2f90c69a9";
      fetchSubmodules = false;
      sha256 = "sha256-ciSQGuNOxDnsrlmByrXk0uPNKy4F+1lInq2e1hEq108=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-10-08";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  masterpdfeditor = {
    pname = "masterpdfeditor";
    version = "5.9.70";
    src = fetchurl {
      url = "https://code-industry.net/public/master-pdf-editor-5.9.70-qt5.x86_64.tar.gz";
      sha256 = "sha256-26Csx/Z9JF49+tvF4NweVClikMTZ25teFQX6hfbHcjw=";
    };
  };
  nix-index = {
    pname = "nix-index";
    version = "3dbd1454abba9bbc94035813d6367b376e0bfb24";
    src = fetchFromGitHub {
      owner = "bennofs";
      repo = "nix-index";
      rev = "3dbd1454abba9bbc94035813d6367b376e0bfb24";
      fetchSubmodules = false;
      sha256 = "sha256-optjx/MoJjpxql9cMLI+hEt6AwcpMOUc6ZCfqQ7KYbQ=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-08-24";
  };
  nix-linter = {
    pname = "nix-linter";
    version = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
    src = fetchgit {
      url = "https://github.com/Synthetica9/nix-linter";
      rev = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wWkRak3bQvE5dY/CXqNelK3XIoHOk48m3pQHWJWKpkI=";
    };
    date = "2021-07-20";
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "a7c8781b5a18026fbc3edb36397931526f243590";
    src = fetchFromGitHub {
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "a7c8781b5a18026fbc3edb36397931526f243590";
      fetchSubmodules = false;
      sha256 = "sha256-JStpIKU+jU6TkXToTONfdEhLjaASGzC+tRmSJRiqKWU=";
    };
    date = "2023-10-09";
  };
  numix-solarized-gtk-theme-git = {
    pname = "numix-solarized-gtk-theme-git";
    version = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
    src = fetchgit {
      url = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git";
      rev = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-r5xCe8Ew+/SuCUaZ0yjlumORTy/y1VwbQQjQ6uEyGsY=";
    };
    date = "2023-03-05";
  };
  open-in-editor = {
    pname = "open-in-editor";
    version = "08057f04a8d025a44974cb83770851b0b9149f82";
    src = fetchgit {
      url = "https://github.com/karlicoss/open-in-editor";
      rev = "08057f04a8d025a44974cb83770851b0b9149f82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x7MqX6GLKsZahXAxbw6mVZ5gQP/Sar9EiHJgqhABW9s=";
    };
    date = "2021-02-28";
  };
  orgparse = {
    pname = "orgparse";
    version = "0.4.20231004";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/orgparse/orgparse-0.4.20231004.tar.gz";
      sha256 = "sha256-pOOK6tq/mYiw9npmrNCCedGCILy8QioSkGDCiQu6kaA=";
    };
  };
  pam_u2f = {
    pname = "pam_u2f";
    version = "1.2.1";
    src = fetchurl {
      url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.2.1.tar.gz";
      sha256 = "sha256-cOdBvKGXtktPvo3R9tV84ritWMp4Y1LFJfPy1EEliUw=";
    };
  };
  pam_usb = {
    pname = "pam_usb";
    version = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
    src = fetchgit {
      url = "https://github.com/mcdope/pam_usb";
      rev = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oSZ0+Cphy1+h6qn8IVKiv91+IhqUUOFnr+Ya+G+wPH0=";
    };
    date = "2023-03-21";
  };
  paper-store = {
    pname = "paper-store";
    version = "638a495e9b56262b981c7b19e82967495bdd1278";
    src = fetchgit {
      url = "https://github.com/nurupo/paper-store";
      rev = "638a495e9b56262b981c7b19e82967495bdd1278";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-aPxao4BZ15m6pEWPYhftbN/6Witu2GSydPforjt2sro=";
    };
    date = "2019-07-05";
  };
  pbkdf2-sha512 = {
    pname = "pbkdf2-sha512";
    version = "b08671a4f559921ef5decf5a71c53feeffb17859";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c";
      sha256 = "sha256-OelyIsDDto6Ir22YY/UM+r9EBx6K8TNdjM3efzUJxE8=";
    };
    date = "2023-12-02";
  };
  promnesia = {
    pname = "promnesia";
    version = "62839c72363bf39455cf33937e7efc81c0bdf5c1";
    src = fetchFromGitHub {
      owner = "karlicoss";
      repo = "promnesia";
      rev = "62839c72363bf39455cf33937e7efc81c0bdf5c1";
      fetchSubmodules = false;
      sha256 = "sha256-YOq1RBJ5+Vi0tytPjLq8l+LSW3sjvNCoPdUIK+crvGw=";
    };
    date = "2023-11-28";
  };
  quicklisp = {
    pname = "quicklisp";
    version = "latest";
    src = fetchurl {
      url = "https://beta.quicklisp.org/quicklisp.lisp";
      sha256 = "sha256-SnpcKuvgcWQXBHhUJnOX4kpE0MzglhJ0EenOnM/rLBc=";
    };
  };
  rainbowsh = {
    pname = "rainbowsh";
    version = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
    src = fetchFromGitHub {
      owner = "xr09";
      repo = "rainbow.sh";
      rev = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
      fetchSubmodules = false;
      sha256 = "sha256-F+Nabc/Fe5ET6lSkdll5YH/mEpKp3OlpaGk+u0rQpPQ=";
    };
    date = "2022-08-24";
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "980d7cc06e9fa51f0060972d4a1d947f8be4cb40";
    src = fetchFromGitHub {
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "980d7cc06e9fa51f0060972d4a1d947f8be4cb40";
      fetchSubmodules = false;
      sha256 = "sha256-8UbyrBkrW0Ma5SOdXDI3nHO+55KV9JT2kVoR8Ft4xtI=";
    };
    date = "2023-11-15";
  };
  rtw89 = {
    pname = "rtw89";
    version = "71c581e92e529998ebbc43c2bbb5a7b088fb98a1";
    src = fetchFromGitHub {
      owner = "lwfinger";
      repo = "rtw89";
      rev = "71c581e92e529998ebbc43c2bbb5a7b088fb98a1";
      fetchSubmodules = false;
      sha256 = "sha256-bmJ40o2+xlgg5Hue1LhmLhcPYxdtqrexZVjUoOiyS1Y=";
    };
    date = "2023-12-01";
  };
  s5cmd = {
    pname = "s5cmd";
    version = "c1c7ee35acfc16aaf4a2b060129aa60b75bb5ef5";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "c1c7ee35acfc16aaf4a2b060129aa60b75bb5ef5";
      fetchSubmodules = false;
      sha256 = "sha256-C6cs7UB+O70Ixuw7EE5LX6B4ND1mVJqth5ZnmNNR3BU=";
    };
    date = "2023-10-12";
  };
  shellspec = {
    pname = "shellspec";
    version = "f800240b606ed8d60f27ca687400836c0083e76a";
    src = fetchFromGitHub {
      owner = "shellspec";
      repo = "shellspec";
      rev = "f800240b606ed8d60f27ca687400836c0083e76a";
      fetchSubmodules = false;
      sha256 = "sha256-PyZBc7bmycV02nTpoDaA40m4DA1IuDmb/eCd3+RAp0o=";
    };
    date = "2022-05-04";
  };
  shflags = {
    pname = "shflags";
    version = "96694d58ce92065fdd8f8761d930765cb9a8d066";
    src = fetchFromGitHub {
      owner = "kward";
      repo = "shflags";
      rev = "96694d58ce92065fdd8f8761d930765cb9a8d066";
      fetchSubmodules = false;
      sha256 = "sha256-IJJEi8xmIco/IuN9LSf6qMacsG6jHQek9F0dPKEwviI=";
    };
    date = "2023-08-24";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "be826cbe2bb11a0675dd71f548ff1396608da7ea";
    src = fetchFromGitHub {
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "be826cbe2bb11a0675dd71f548ff1396608da7ea";
      fetchSubmodules = false;
      sha256 = "sha256-473Srq7aDe4R9UIVdQiG0P4vXNRPtg0r8Vgc+HIxZMQ=";
    };
    date = "2023-10-10";
  };
  stumpwm = {
    pname = "stumpwm";
    version = "189a730f73266999d5b8f992faf939c11d7815ad";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "189a730f73266999d5b8f992faf939c11d7815ad";
      fetchSubmodules = false;
      sha256 = "sha256-jPxMo3QfqfSYTkKYnCf6CQhkSJrX90p70amSXynBxnE=";
    };
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "54dfbeb553ad68272163c520655b6a4af4ad0430";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm-contrib";
      rev = "54dfbeb553ad68272163c520655b6a4af4ad0430";
      fetchSubmodules = false;
      sha256 = "sha256-kaI6B3TWSRBlVtzO4MZAJC08Xo6206J0MuTyKglaAqQ=";
    };
    date = "2023-10-26";
  };
  stumpwm-git = {
    pname = "stumpwm-git";
    version = "b3a0e2d067da839453ca3a4581e7d5957677cac3";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "b3a0e2d067da839453ca3a4581e7d5957677cac3";
      fetchSubmodules = false;
      sha256 = "sha256-sWCr3wm99Hv4LsZ572921wcUnQV40AmWSUVMWnmfeSo=";
    };
    asd = "stumpwm";
    system = "stumpwm";
    date = "2023-11-24";
  };
  tfenv = {
    pname = "tfenv";
    version = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
      fetchSubmodules = false;
      sha256 = "sha256-UNvLJQB47IRcNZpoUGXTW2g63ApijnIB3oUb7Zu4lUY=";
    };
    date = "2022-10-01";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
  trezor-agent = {
    pname = "trezor-agent";
    version = "v0.14.8";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "trezor-agent";
      rev = "v0.14.8";
      fetchSubmodules = false;
      sha256 = "sha256-tcVott/GlHsICQf640Gm5jx89fZWsCdcYnBxi/Kh2oc=";
    };
  };
  trezor-agent-subkeys = {
    pname = "trezor-agent-subkeys";
    version = "eac2f8215f2c11a92faf30170277c57bb7289801";
    src = fetchgit {
      url = "https://github.com/jrruethe/trezor-agent";
      rev = "eac2f8215f2c11a92faf30170277c57bb7289801";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DA5REsNQNykpbCFb6PJbgEBYiDh1kEq083wRZq+pIQM=";
    };
    date = "2023-06-09";
  };
  trezor-gpg-pinentry-tk = {
    pname = "trezor-gpg-pinentry-tk";
    version = "0.0.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/trezor-gpg-pinentry-tk/trezor-gpg-pinentry-tk-0.0.10.tar.gz";
      sha256 = "sha256-h/NJKbKBP5Sbq0BYJes1h2ka2/k2gSUr564qOQZeAc4=";
    };
  };
}
