[transmissionic]
# Remote for Transmission Daemon
src.github = "6c65726f79/Transmissionic"
fetch.url = "https://github.com/6c65726f79/Transmissionic/releases/download/$ver/Transmissionic-webui-$ver.zip"

[tfenv]
#  Terraform version manager
src.git = "https://github.com/tfutils/tfenv"
fetch.github = "tfutils/tfenv"

[s5cmd]
# Parallel S3 and local filesystem execution tool.
src.git = "https://github.com/peak/s5cmd"
fetch.github = "peak/s5cmd"

####################
# nvfetcher.toml
[chatgpt-wrapper]
src.git = "https://github.com/mmabrouk/chatgpt-wrapper"
fetch.github = "mmabrouk/chatgpt-wrapper"

[langchain]
src.pypi = "langchain"
fetch.pypi = "langchain"

# [StevenBlack-hosts]
# src.git = "https://github.com/StevenBlack/hosts"
# fetch.github = "StevenBlack/hosts"
# [brave]
# src.github = "brave/brave-browser"
# fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_amd64.deb"
# src.prefix = "v"
[drawio]
src.github = "jgraph/drawio-desktop"
fetch.url = "https://github.com/jgraph/drawio-desktop/releases/download/v$ver/drawio-x86_64-$ver.rpm"
src.prefix = "v"

# [wezterm-appimage]
# src.cmd = "date +%m-%d-%Y"
# fetch.url = "https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-Ubuntu18.04.AppImage"
[adguardhome]
src.github = "AdguardTeam/AdGuardHome"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/$ver/AdGuardHome_linux_amd64.tar.gz"

[spaceship-prompt]
src.git = "https://github.com/spaceship-prompt/spaceship-prompt"
fetch.github = "spaceship-prompt/spaceship-prompt"

### :START: promnesia
[promnesia]
src.git = "https://github.com/karlicoss/promnesia"
fetch.github = "karlicoss/promnesia"

[HPI]
src.pypi = "HPI"
fetch.pypi = "HPI"

[hug]
src.pypi = "hug"
fetch.pypi = "hug"

[orgparse]
src.pypi = "orgparse"
fetch.pypi = "orgparse"

[open-in-editor]
src.git = "https://github.com/karlicoss/open-in-editor"
fetch.git = "https://github.com/karlicoss/open-in-editor"

### :END: promnesia
[logseq]
# A privacy-first, open-source platform for knowledge management and collaboration
src.github = "logseq/logseq"
fetch.url = "https://github.com/logseq/logseq/releases/download/$ver/logseq-linux-x64-$ver.AppImage"

###################
# Pkgs and overlays
#
[pam_u2f]
src.manual = "1.2.1"
fetch.url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-$ver.tar.gz"

[pam_usb]
src.git = "https://github.com/mcdope/pam_usb"
fetch.git = "https://github.com/mcdope/pam_usb"

[gpg-hd]
# src.git = "https://github.com/voobscout/gpg-hd"
# fetch.github = "voobscout/gpg-hd"
src.git = "https://github.com/Logicwax/gpg-hd"
fetch.github = "Logicwax/gpg-hd"

[trezor-agent]
src.github_tag = "romanz/trezor-agent"
src.use_latest_tag = true
# src.manual = "v0.14.5"
fetch.github = "romanz/trezor-agent"

# NOTE: pypi has an older version!
# src.pypi = "trezor_agent"
# fetch.pypi = "trezor_agent"
[trezor-agent-subkeys]
src.git = "https://github.com/jrruethe/trezor-agent"
src.branch = "subkeys"
fetch.git = "https://github.com/jrruethe/trezor-agent"

[trezor-gpg-pinentry-tk]
src.pypi = "trezor-gpg-pinentry-tk"
fetch.pypi = "trezor-gpg-pinentry-tk"

[age-plugin-trezor]
src.git = "https://github.com/romanz/age-plugin-trezor"
fetch.github = "romanz/age-plugin-trezor"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[dbus-listen]
src.git = "https://github.com/voobscout/dbus-listen"
fetch.git = "https://github.com/voobscout/dbus-listen"

# [rofi-themes-extra]
# src.git = "https://github.com/davatorium/rofi-themes"
# fetch.git = "https://github.com/davatorium/rofi-themes"
[git-get]
src.git = "https://github.com/grdl/git-get"
fetch.github = "grdl/git-get"
passthru = { vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b" }

[shflags]
src.git = "https://github.com/kward/shflags"
fetch.github = "kward/shflags"

[shellspec]
src.git = "https://github.com/shellspec/shellspec"
fetch.github = "shellspec/shellspec"

[getoptions]
src.git = "https://github.com/ko1nksm/getoptions"
fetch.github = "ko1nksm/getoptions"

[rainbowsh]
src.git = "https://github.com/xr09/rainbow.sh"
fetch.github = "xr09/rainbow.sh"

[git-remote-ipfs]
src.git = "https://github.com/bqv/git-remote-ipfs"
fetch.github = "bqv/git-remote-ipfs"
passthru = { vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=" }

[git-pull-request-mirror]
src.git = "https://github.com/google/git-pull-request-mirror"
fetch.github = "google/git-pull-request-mirror"
passthru = { vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn" }

######
### kubernetes
######
# [k9s]
# src.github = "derailed/k9s"
# src.use_latest_release = true
# fetch.github = "derailed/k9s"
### cloud and friends
# [vultr-cli]
# src.github = "vultr/vultr-cli"
# src.use_latest_release = true
# fetch.github = "vultr/vultr-cli"
#[cl-qrencode]
#src.git = "https://github.com/jnjcc/cl-qrencode"
#src.branch ="master"
#fetch.github = "jnjcc/cl-qrencode"
########
[nix-index]
src.git = "https://github.com/bennofs/nix-index"
fetch.github = "bennofs/nix-index"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[nix-linter]
src.git = "https://github.com/Synthetica9/nix-linter"
fetch.git = "https://github.com/Synthetica9/nix-linter"

[lorri]
src.git = "https://github.com/nix-community/lorri"
src.branch = "canon"
fetch.github = "nix-community/lorri"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[console-solarized]
src.git = "https://github.com/adeverteuil/console-solarized"
fetch.github = "adeverteuil/console-solarized"

[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
src.branch = "master"
fetch.github = "haslersn/any-nix-shell"

[nix-zsh-completions]
src.git = "https://github.com/spwhitt/nix-zsh-completions"
src.branch = "master"
fetch.github = "spwhitt/nix-zsh-completions"

# lisp overlays stuff
[stumpwm-git]
src.git = "https://github.com/stumpwm/stumpwm"
fetch.github = "stumpwm/stumpwm"
passthru = { system = "stumpwm", asd = "stumpwm" }

[quicklisp]
src.manual = "latest"
fetch.url = "https://beta.quicklisp.org/quicklisp.lisp"

# FIXME: broken nix builds after 189a730f73266999d5b8f992faf939c11d7815ad
[stumpwm]
src.manual = "189a730f73266999d5b8f992faf939c11d7815ad"
# src.git = "https://github.com/stumpwm/stumpwm"
fetch.github = "stumpwm/stumpwm"

[stumpwm-contrib]
src.git = "https://github.com/stumpwm/stumpwm-contrib"
fetch.github = "stumpwm/stumpwm-contrib"

[dbus]
src.git = "https://github.com/death/dbus"
fetch.git = "https://github.com/death/dbus"

[cl-hash-util]
src.git = "https://github.com/orthecreedence/cl-hash-util"
fetch.github = "orthecreedence/cl-hash-util"

[cl-strings]
src.git = "https://github.com/diogoalexandrefranco/cl-strings"
fetch.github = "diogoalexandrefranco/cl-strings"

[cl-shellwords]
src.git = "https://github.com/jorams/cl-shellwords"
fetch.github = "jorams/cl-shellwords"

[listopia]
src.git = "https://github.com/Dimercel/listopia"
fetch.github = "Dimercel/listopia"

[acl-compat]
src.git = "https://git.code.sf.net/p/portableaserve/git"
fetch.git = "https://git.code.sf.net/p/portableaserve/git"

[cl-syslog]
src.git = "https://github.com/lhope/cl-syslog"
fetch.github = "lhope/cl-syslog"

# hardware stuff
[rtl88x2bu]
src.git = "https://github.com/RinCat/RTL88x2BU-Linux-Driver"
fetch.github = "RinCat/RTL88x2BU-Linux-Driver"

[rtw89]
src.git = "https://github.com/lwfinger/rtw89"
fetch.github = "lwfinger/rtw89"

# hardware crypto stuff
[paper-store]
src.git = "https://github.com/nurupo/paper-store"
fetch.git = "https://github.com/nurupo/paper-store"

[pbkdf2-sha512]
src.git = "https://github.com/NixOS/nixpkgs"
fetch.url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c"

# [age-plugin-yubikey]
# src.git = "https://github.com/str4d/age-plugin-yubikey"
# fetch.git = "https://github.com/str4d/age-plugin-yubikey"
# cargo_locks = [ "Cargo.lock" ]
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }
# themes
# [sublimeSolarized]
# src.github = "braver/Solarized"
# fetch.github = "braver/Solarized"
# [numix-solarized-gtk-theme-bin]
# src.github = "Ferdi265/numix-solarized-gtk-theme"
# src.use_latest_release = true
# fetch.url = "https://github.com/Ferdi265/numix-solarized-gtk-theme/releases/download/20210831/NumixSolarized-20210831.tar.gz"
[numix-solarized-gtk-theme-git]
src.git = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git"
fetch.git = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git"

# Office apps
[masterpdfeditor]
src.manual = "5.9.70"
fetch.url = "https://code-industry.net/public/master-pdf-editor-$ver-qt5.x86_64.tar.gz"
