# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lidarr = {
    pname = "lidarr";
    version = "2.13.3.4711";
    src = fetchurl {
      url = "https://github.com/lidarr/Lidarr/releases/download/v2.13.3.4711/Lidarr.master.2.13.3.4711.linux-core-arm64.tar.gz";
      sha256 = "sha256-ck2AspRkKm8hdzO70acTGUUd8WTOevIJF50YwQf/R20=";
    };
  };
  prowlarr = {
    pname = "prowlarr";
    version = "2.0.5.5160";
    src = fetchurl {
      url = "https://github.com/Prowlarr/Prowlarr/releases/download/v2.0.5.5160/Prowlarr.master.2.0.5.5160.linux-core-arm64.tar.gz";
      sha256 = "sha256-fGbLgThVJ5SmgcxhJSjZvywq8PPzPITC6wW+ltZifwk=";
    };
  };
  radarr = {
    pname = "radarr";
    version = "5.27.5.10198";
    src = fetchurl {
      url = "https://github.com/Radarr/Radarr/releases/download/v5.27.5.10198/Radarr.master.5.27.5.10198.linux-core-arm64.tar.gz";
      sha256 = "sha256-3EFJu613PwO8z10DxVyoHcnhGDs63ny/PndQzipGJII=";
    };
  };
  readarr = {
    pname = "readarr";
    version = "0.4.13.2760";
    src = fetchurl {
      url = "https://github.com/Readarr/Readarr/releases/download/v0.4.13.2760/Readarr.develop.0.4.13.2760.linux-core-arm64.tar.gz";
      sha256 = "sha256-qYG1uFyn26J6ElTeeI8Ozf6kVhm6EZKKMJ+4UFRhlqQ=";
    };
  };
  sonarr = {
    pname = "sonarr";
    version = "4.0.15.2941";
    src = fetchurl {
      url = "https://github.com/Sonarr/Sonarr/releases/download/v4.0.15.2941/Sonarr.main.4.0.15.2941.linux-arm64.tar.gz";
      sha256 = "sha256-L6ukLTaXkXNhJuUR85T6EpzxRCS5eMyYCbygRWMJCQ8=";
    };
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
}
