# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
      fetchSubmodules = false;
      sha256 = "sha256-EYhFrOo0j0JSNTdcZCbyM0iLxaymUXi1u6jZy8lTOaY=";
    };
    date = "2023-12-06";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "19aed6ca81a3b1e549f47867c924d180d8536791";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "19aed6ca81a3b1e549f47867c924d180d8536791";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FZmWuu64D08kysLa/LU8o3W60s6/0FeQbVL923mJd1k=";
    };
    date = "2024-03-13";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "39ef44f810c34e8900978788467cc675870bcd19";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "39ef44f810c34e8900978788467cc675870bcd19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SlqJ8erFtiydEdgZFGJ23DQ9fZH4FF09iO6t3gf5pwE=";
    };
    date = "2024-06-23";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "7281b44bcfbaf1c43e0d326bcf5364f3114fa133";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "7281b44bcfbaf1c43e0d326bcf5364f3114fa133";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-KkeTbC+iqSrwlVkojhxKd0GEh5QW29TqJt9H3jePvIM=";
    };
    date = "2024-06-29";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "e15bafa95b39091dbb2a99ad62e42f03a8d78f01";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "e15bafa95b39091dbb2a99ad62e42f03a8d78f01";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-jKm+oVMadHyeG93VFU3JG3qNROOJPDXs7w2pIO/2IyM=";
    };
    date = "2024-07-03";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "b0e1e68e78429659f6fd3b26e6691e921fa0d7e1";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "b0e1e68e78429659f6fd3b26e6691e921fa0d7e1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-+HLEV9VCk3nXTWYypdWgLcPEW67xX+zedfObkB1oB0U=";
    };
    date = "2024-07-11";
  };
  grip = {
    pname = "grip";
    version = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
    src = fetchgit {
      url = "https://github.com/joeyespo/grip";
      rev = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZOkuzGXgNJw9tj7/MATBojEmDszK7FcYyYKy59Qo19I=";
    };
    date = "2023-10-12";
  };
  jinx = {
    pname = "jinx";
    version = "e39f2682ea902a1d06bd118d5899b2bbadfb6dce";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "e39f2682ea902a1d06bd118d5899b2bbadfb6dce";
      fetchSubmodules = false;
      sha256 = "sha256-RD2n2AkKJRsQDGDPwl8k41YAfh+nfFzyjquTx57GwjM=";
    };
    date = "2024-07-08";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "212bbf84a6556acc93b47028c771656e3e772196";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "212bbf84a6556acc93b47028c771656e3e772196";
      fetchSubmodules = false;
      sha256 = "sha256-e6BmYsjOCl7c3cbYxxbMU3YlWvDIlMLgsRnxnLd4tUU=";
    };
    date = "2024-07-10";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "59ad17690576190811e0746c12ad6809596ca3ac";
    src = fetchFromGitHub {
      owner = "remi-gelinas";
      repo = "nix-ts-mode";
      rev = "59ad17690576190811e0746c12ad6809596ca3ac";
      fetchSubmodules = false;
      sha256 = "sha256-DtYAsAeKSYjDzGes504Bq538OUG8HQSiJf+GjeDuMDE=";
    };
    date = "2024-07-10";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
}
