# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
      fetchSubmodules = false;
      sha256 = "sha256-EYhFrOo0j0JSNTdcZCbyM0iLxaymUXi1u6jZy8lTOaY=";
    };
    date = "2023-12-06";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "19aed6ca81a3b1e549f47867c924d180d8536791";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "19aed6ca81a3b1e549f47867c924d180d8536791";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FZmWuu64D08kysLa/LU8o3W60s6/0FeQbVL923mJd1k=";
    };
    date = "2024-03-13";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "39ef44f810c34e8900978788467cc675870bcd19";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "39ef44f810c34e8900978788467cc675870bcd19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SlqJ8erFtiydEdgZFGJ23DQ9fZH4FF09iO6t3gf5pwE=";
    };
    date = "2024-06-23";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "1bb68a2bc799ab7c1c35cd491d397bef94e8cfbb";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "1bb68a2bc799ab7c1c35cd491d397bef94e8cfbb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gifae7Y3CrhyRRnENbD9t5Lu/I3wXKQeaKd/IW6B7bc=";
    };
    date = "2024-07-14";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "eedd881fd9b3574d77ec2499f877dc26d875fffb";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "eedd881fd9b3574d77ec2499f877dc26d875fffb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GgmjxuDIq8LUhf2D3He5obgreLUqO9N/4/xn0iF7cFo=";
    };
    date = "2024-07-12";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "36e7aaa619342eff61b1daf3ac664f94d5272db7";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "36e7aaa619342eff61b1daf3ac664f94d5272db7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-DN3pCPN1uISI5KPf5b8AGkmafs4ojE7JKFoShd6ZaK8=";
    };
    date = "2024-07-18";
  };
  grip = {
    pname = "grip";
    version = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
    src = fetchgit {
      url = "https://github.com/joeyespo/grip";
      rev = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZOkuzGXgNJw9tj7/MATBojEmDszK7FcYyYKy59Qo19I=";
    };
    date = "2023-10-12";
  };
  jinx = {
    pname = "jinx";
    version = "54730c6187f8ef866b23693f9c44f28df504194b";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "54730c6187f8ef866b23693f9c44f28df504194b";
      fetchSubmodules = false;
      sha256 = "sha256-4FZPFlsVZGv+AmZxXRGwUHuUOFYk0aFY9c+9gjLoJS0=";
    };
    date = "2024-07-18";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "023924926ae6adfbcf5458c350b90dea7c05d51b";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "023924926ae6adfbcf5458c350b90dea7c05d51b";
      fetchSubmodules = false;
      sha256 = "sha256-59bl4YbKS3HgrGJlUfM3LPabxKuuE+dT7CnVUJIl05k=";
    };
    date = "2024-07-14";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "59ad17690576190811e0746c12ad6809596ca3ac";
    src = fetchFromGitHub {
      owner = "remi-gelinas";
      repo = "nix-ts-mode";
      rev = "59ad17690576190811e0746c12ad6809596ca3ac";
      fetchSubmodules = false;
      sha256 = "sha256-DtYAsAeKSYjDzGes504Bq538OUG8HQSiJf+GjeDuMDE=";
    };
    date = "2024-07-10";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
}
