# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "1851d8fa2a27d3fd8deeeb29cd21c3002b8351ba";
      fetchSubmodules = false;
      sha256 = "sha256-EYhFrOo0j0JSNTdcZCbyM0iLxaymUXi1u6jZy8lTOaY=";
    };
    date = "2023-12-06";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "19aed6ca81a3b1e549f47867c924d180d8536791";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "19aed6ca81a3b1e549f47867c924d180d8536791";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-FZmWuu64D08kysLa/LU8o3W60s6/0FeQbVL923mJd1k=";
    };
    date = "2024-03-13";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "39ef44f810c34e8900978788467cc675870bcd19";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "39ef44f810c34e8900978788467cc675870bcd19";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SlqJ8erFtiydEdgZFGJ23DQ9fZH4FF09iO6t3gf5pwE=";
    };
    date = "2024-06-23";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "81ba1c5d8d70480c472c364aeee4281ac339f470";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "81ba1c5d8d70480c472c364aeee4281ac339f470";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-nKISuXpR8Rr7vAjdGwzN/BAltzWbdOy6zoE5lDaRR3w=";
    };
    date = "2024-08-11";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "535ef61e82f09d744cd5b097b1fc99f08cce175c";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "535ef61e82f09d744cd5b097b1fc99f08cce175c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/ZDnEZWUFcKnUtFrd/4C7LX16GAdUQncU8ZnYzntKS0=";
    };
    date = "2024-08-16";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "559e5b6a966fa82bf8322f89d78a00ef4181812a";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "559e5b6a966fa82bf8322f89d78a00ef4181812a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-Wk0piemQp7OCevCrzHn3QZXYpjmUHzraNXb5GPsZjmo=";
    };
    date = "2024-09-03";
  };
  grip = {
    pname = "grip";
    version = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
    src = fetchgit {
      url = "https://github.com/joeyespo/grip";
      rev = "a3f0ab5c8942ac15cf68f790b80c0a43b3a4c71e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZOkuzGXgNJw9tj7/MATBojEmDszK7FcYyYKy59Qo19I=";
    };
    date = "2023-10-12";
  };
  jinx = {
    pname = "jinx";
    version = "cd827ee199efedc8f5e094001d90206e698f91e8";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "cd827ee199efedc8f5e094001d90206e698f91e8";
      fetchSubmodules = false;
      sha256 = "sha256-s6DQ9UlQ98071n+nbhcRU2J2qgNosiJxqC4FTazwkww=";
    };
    date = "2024-08-24";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "0c02dc44f9bdf86f93ee3a5fbe624bf5a556b807";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "0c02dc44f9bdf86f93ee3a5fbe624bf5a556b807";
      fetchSubmodules = false;
      sha256 = "sha256-zgmGrgc+BHwwo6ouYGBq9fClRwt9rIYET5ExfWWgNPI=";
    };
    date = "2024-09-04";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  nix-ts-mode = {
    pname = "nix-ts-mode";
    version = "59ad17690576190811e0746c12ad6809596ca3ac";
    src = fetchFromGitHub {
      owner = "remi-gelinas";
      repo = "nix-ts-mode";
      rev = "59ad17690576190811e0746c12ad6809596ca3ac";
      fetchSubmodules = false;
      sha256 = "sha256-DtYAsAeKSYjDzGes504Bq538OUG8HQSiJf+GjeDuMDE=";
    };
    date = "2024-07-10";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
}
