# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nyxt-el = {
    pname = "nyxt-el";
    version = "955c0a06e81d681f719c63ede65069394d521cdc";
    src = fetchgit {
      url = "https://github.com/migalmoreno/nyxt.el";
      rev = "955c0a06e81d681f719c63ede65069394d521cdc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xgDVbMI3xiHkne52pRJJhFYTBEl79cd4jEcFqmMy9hM=";
    };
    date = "2025-11-16";
  };
  nyxt-ext_nx-ace = {
    pname = "nyxt-ext_nx-ace";
    version = "83aac18448c05fc9ef1ff5058c3def668dc8d81a";
    src = fetchgit {
      url = "https://github.com/atlas-engineer/nx-ace";
      rev = "83aac18448c05fc9ef1ff5058c3def668dc8d81a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+/utlTZ/dvc2N/7whjMaE+Iv1HQGKa24gL2Hl8ASaYs=";
    };
    date = "2023-06-30";
  };
  nyxt-ext_nx-dark-reader = {
    pname = "nyxt-ext_nx-dark-reader";
    version = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
    src = fetchgit {
      url = "https://github.com/aartaka/nx-dark-reader";
      rev = "57dc1a9482a81d7c15b00c4b9d647bf1b129d8e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CKJGCk7ATd0naFhill5rrvay6V2JE4Bstu4tFpaAjB0=";
    };
    date = "2023-06-20";
  };
  nyxt-ext_nx-reader = {
    pname = "nyxt-ext_nx-reader";
    version = "cb08d2a1c794c8a9942bc5e7b793b2811a025074";
    src = fetchgit {
      url = "https://github.com/atlas-engineer/nx-reader";
      rev = "cb08d2a1c794c8a9942bc5e7b793b2811a025074";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v0EPZKNfpKvY3LD1YZBuU//4/wCXJRyE8WBJBknfL/M=";
    };
    date = "2020-06-14";
  };
  nyxt-ext_nx-search-engines = {
    pname = "nyxt-ext_nx-search-engines";
    version = "f81f47df82f8e322f0a8919d05fc513297095a0b";
    src = fetchgit {
      url = "https://github.com/aartaka/nx-search-engines";
      rev = "f81f47df82f8e322f0a8919d05fc513297095a0b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Q+6B3lDzlhfHnS306yLh5LpxdIXESdH/Y2D3GJodbXs=";
    };
    date = "2023-06-07";
  };
  nyxt-ext_nx-tailor = {
    pname = "nyxt-ext_nx-tailor";
    version = "2fa070a7636ad848a61e8e9126dac6c04256df7d";
    src = fetchgit {
      url = "https://github.com/migalmoreno/nx-tailor";
      rev = "2fa070a7636ad848a61e8e9126dac6c04256df7d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gk18rqcYY2H28NymxDKUnB03PfcFTa1rTShst5WxIrs=";
    };
    date = "2025-11-16";
  };
}
