# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rock-pi-x-firmware = {
    pname = "rock-pi-x-firmware";
    version = "20200828-0711";
    src = fetchurl {
      url = "https://dl.radxa.com/rockpix/drivers/firmware/AP6255_BT_WIFI_Firmware.zip";
      sha256 = "sha256-G5Q0/N02G3eO/+S1ELhOcX4+znWJz67FXsiUTvmDYAM=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "471877314bd3e4b4a02896a8ffa98fb09559c72f";
    src = fetchFromGitHub {
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "471877314bd3e4b4a02896a8ffa98fb09559c72f";
      fetchSubmodules = false;
      sha256 = "sha256-P6MnpkWInsOwn9RhPmH7QbGqK7ezJlzp84q7GBoI41g=";
    };
    date = "2025-10-09";
  };
  rtw89 = {
    pname = "rtw89";
    version = "d1fced1b8a741dc9f92b47c69489c24385945f6e";
    src = fetchFromGitHub {
      owner = "lwfinger";
      repo = "rtw89";
      rev = "d1fced1b8a741dc9f92b47c69489c24385945f6e";
      fetchSubmodules = false;
      sha256 = "sha256-Htu1TihKkUCNWw5LCf+cnGyCQsj0PuijlfAolug2MC8=";
    };
    date = "2024-08-24";
  };
}
