# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lobe-chat = {
    pname = "lobe-chat";
    version = "v1.43.1";
    src = dockerTools.pullImage {
      imageName = "lobehub/lobe-chat";
      imageDigest = "sha256:195619f203c7e4fb2dbd6788fe03aff0c2d05c8530040430e9ad796e86b485a4";
      sha256 = "sha256-15wfsdj4ZdpVxZ9+PhrWEnZe71LxckZM5wzNpT+csRU=";
      finalImageTag = "latest";
    };
  };
  rock-pi-x-firmware = {
    pname = "rock-pi-x-firmware";
    version = "20200828-0711";
    src = fetchurl {
      url = "https://dl.radxa.com/rockpix/drivers/firmware/AP6255_BT_WIFI_Firmware.zip";
      sha256 = "sha256-G5Q0/N02G3eO/+S1ELhOcX4+znWJz67FXsiUTvmDYAM=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "2092b8d80d7fb7fa953d9dd3d666e5679c99a2f8";
    src = fetchFromGitHub {
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "2092b8d80d7fb7fa953d9dd3d666e5679c99a2f8";
      fetchSubmodules = false;
      sha256 = "sha256-z3yZqAN0pbAgWrbqoJb+wkY3gxAj8oUwFyaUmwYk82o=";
    };
    date = "2024-12-01";
  };
  rtw89 = {
    pname = "rtw89";
    version = "d1fced1b8a741dc9f92b47c69489c24385945f6e";
    src = fetchFromGitHub {
      owner = "lwfinger";
      repo = "rtw89";
      rev = "d1fced1b8a741dc9f92b47c69489c24385945f6e";
      fetchSubmodules = false;
      sha256 = "sha256-Htu1TihKkUCNWw5LCf+cnGyCQsj0PuijlfAolug2MC8=";
    };
    date = "2024-08-24";
  };
}
