# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rock-pi-x-firmware = {
    pname = "rock-pi-x-firmware";
    version = "20200828-0711";
    src = fetchurl {
      url = "https://dl.radxa.com/rockpix/drivers/firmware/AP6255_BT_WIFI_Firmware.zip";
      sha256 = "sha256-G5Q0/N02G3eO/+S1ELhOcX4+znWJz67FXsiUTvmDYAM=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "bf52727c417343b32b8712a5d0679dd218f324fe";
    src = fetchFromGitHub {
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "bf52727c417343b32b8712a5d0679dd218f324fe";
      fetchSubmodules = false;
      sha256 = "sha256-JYm2gZNVpK868MCfJu7nZK+h7gjsFO5XuHOGbOVimuA=";
    };
    date = "2024-07-11";
  };
  rtw89 = {
    pname = "rtw89";
    version = "239cc6670a67a1e7b6f43bd681efdfedf6a53bb1";
    src = fetchFromGitHub {
      owner = "lwfinger";
      repo = "rtw89";
      rev = "239cc6670a67a1e7b6f43bd681efdfedf6a53bb1";
      fetchSubmodules = false;
      sha256 = "sha256-JYm2gZNVpK868MCfJu7nZK+h7gjsFO5XuHOGbOVimuA=";
    };
    date = "2024-05-07";
  };
}
