[rock-pi-x-firmware]
src.manual = "20200828-0711"
fetch.url = "https://dl.radxa.com/rockpix/drivers/firmware/AP6255_BT_WIFI_Firmware.zip"

[rtl88x2bu]
# USB wifi stick
src.git = "https://github.com/RinCat/RTL88x2BU-Linux-Driver"
fetch.github = "RinCat/RTL88x2BU-Linux-Driver"

[rtw89]
# PCI wifi card
src.git = "https://github.com/lwfinger/rtw89"
fetch.github = "lwfinger/rtw89"

[lobe-chat]
src.container = "lobehub/lobe-chat"
fetch.docker = "lobehub/lobe-chat"
docker.finalImageTag = "latest"
# docker.arch = ""
# docker pull lobehub/lobe-chat
# [gnupg-git]
# # TODO: refs/tags/gnupg-2.4.5
# src.git = "https://git.gnupg.org/gnupg.git"
# fetch.git = "https://git.gnupg.org/gnupg.git"
