# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "d83ff0a4ae4503bc56b7ed48cd142c3dd423ad3b";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "d83ff0a4ae4503bc56b7ed48cd142c3dd423ad3b";
      fetchSubmodules = false;
      sha256 = "sha256-7nXoYgwV354T42QM9LA9U0xlG2f4Gc7I1inaEG/HwTI=";
    };
    date = "2025-04-28";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "da7d16e9a9d6573727c15205dbbd32b337c02a6f";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "da7d16e9a9d6573727c15205dbbd32b337c02a6f";
      fetchSubmodules = false;
      sha256 = "sha256-Sj53j72W4u5rwqrijxBVS+GeHPItdksWiBy9uSPmWnc=";
    };
    date = "2025-06-27";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "1083eea307074161211162b9cbe1c5c8abec44b2";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "1083eea307074161211162b9cbe1c5c8abec44b2";
      fetchSubmodules = false;
      sha256 = "sha256-68HIAhxJ/8/fcr7oxp/k4AOEATH3o15BUP2QyxYQuF8=";
    };
    date = "2025-07-05";
  };
}
