# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "075b54d5229d0894109e7cbb4bb890bc48bb37e8";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "075b54d5229d0894109e7cbb4bb890bc48bb37e8";
      fetchSubmodules = false;
      sha256 = "sha256-+7dHUIXRsoy9CCHApmCnGuMjhGx/VhleI+zwB7E+5lU=";
    };
    date = "2024-02-15";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "9b9b7f435196208e908f864a2a41e8df29ac5c36";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "9b9b7f435196208e908f864a2a41e8df29ac5c36";
      fetchSubmodules = false;
      sha256 = "sha256-r/EdlYEdmGfLmL+vR6ERair9toUdG2k6SxglyglGd/Q=";
    };
    date = "2024-03-11";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "ac14a2ff7c403029ea5b9d2940143b11fc194fc8";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "ac14a2ff7c403029ea5b9d2940143b11fc194fc8";
      fetchSubmodules = false;
      sha256 = "sha256-XsGTHzQJCoUWQ9jDa0yY7+hFuWre04rizI919AT49Bc=";
    };
    date = "2024-03-19";
  };
}
