# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
      fetchSubmodules = false;
      sha256 = "sha256-p0/inkHPRUkxSIsTmj7VI7sIaX7OXdqjMGZ31W7cnt4=";
    };
    date = "2024-04-18";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "c8351a09174f143424884081a69b6dd8018f4ba3";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "c8351a09174f143424884081a69b6dd8018f4ba3";
      fetchSubmodules = false;
      sha256 = "sha256-CsmKdluHsy7uHQSfV1tXizEkORqLKWvhKPf4usN8xhg=";
    };
    date = "2024-05-17";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "2bb7db5314a91e877d72377d958a5a5a6a8ccf4a";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "2bb7db5314a91e877d72377d958a5a5a6a8ccf4a";
      fetchSubmodules = false;
      sha256 = "sha256-LdLJA4MxcqZID+XsGkYJie8eBFA7CkEnOxAAPD9LGfs=";
    };
    date = "2024-05-24";
  };
}
