# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bash-ide-vscode = {
    pname = "bash-ide-vscode";
    version = "1.41.0";
    src = fetchurl {
      url = "https://mads-hartmann.gallery.vsassets.io/_apis/public/gallery/publisher/mads-hartmann/extension/bash-ide-vscode/1.41.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bash-ide-vscode-1.41.0.zip";
      sha256 = "sha256-glaoBIYnjl5yXA804htdbnbsgLjJyyChel0AIdN0hD0=";
    };
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
  };
  codium = {
    pname = "codium";
    version = "0.8.10";
    src = fetchurl {
      url = "https://Codium.gallery.vsassets.io/_apis/public/gallery/publisher/Codium/extension/codium/0.8.10/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codium-0.8.10.zip";
      sha256 = "sha256-uI9ZKJiODc6JSlv2rt3bNucpOjK2SM4E3TwD6Rz98/0=";
    };
    publisher = "Codium";
    name = "codium";
  };
  copilot = {
    pname = "copilot";
    version = "1.194.894";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.194.894/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.194.894.zip";
      sha256 = "sha256-k8DCvA8lJiWCmabPmZmXkbSUt9kG/MgWnoYYjqJwhjY=";
    };
    publisher = "GitHub";
    name = "copilot";
  };
  cucumberautocomplete = {
    pname = "cucumberautocomplete";
    version = "3.0.0";
    src = fetchurl {
      url = "https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cucumberautocomplete-3.0.0.zip";
      sha256 = "sha256-zoxZd6QL8P+hTuzAuckMurH3SMEco+AYoR/PBzO3cHs=";
    };
    publisher = "alexkrechik";
    name = "cucumberautocomplete";
  };
  emacs-mcx = {
    pname = "emacs-mcx";
    version = "0.61.0";
    src = fetchurl {
      url = "https://tuttieee.gallery.vsassets.io/_apis/public/gallery/publisher/tuttieee/extension/emacs-mcx/0.61.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "emacs-mcx-0.61.0.zip";
      sha256 = "sha256-W0NJyvwQ/+SQEUeK+BY9NT3fx2Du2kH6D979xhdcYSw=";
    };
    publisher = "tuttieee";
    name = "emacs-mcx";
  };
  fonted = {
    pname = "fonted";
    version = "0.0.7";
    src = fetchurl {
      url = "https://degreat.gallery.vsassets.io/_apis/public/gallery/publisher/degreat/extension/fonted/0.0.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "fonted-0.0.7.zip";
      sha256 = "sha256-mW3gC0pzMp53jx8KhkBqyFYxTIq1rcjRmfkeouZsH4A=";
    };
    publisher = "degreat";
    name = "fonted";
  };
  gherkintablealign = {
    pname = "gherkintablealign";
    version = "1.0.2";
    src = fetchurl {
      url = "https://AlanCole.gallery.vsassets.io/_apis/public/gallery/publisher/AlanCole/extension/gherkintablealign/1.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gherkintablealign-1.0.2.zip";
      sha256 = "sha256-AhCm/GyleEOW9NlzE9uSJKIjM8RKQBjSM+RS1j3jiRM=";
    };
    publisher = "AlanCole";
    name = "gherkintablealign";
  };
  haml = {
    pname = "haml";
    version = "1.0.1";
    src = fetchurl {
      url = "https://vayan.gallery.vsassets.io/_apis/public/gallery/publisher/vayan/extension/haml/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "haml-1.0.1.zip";
      sha256 = "sha256-KTsKUfo7bfwqVMSAjRYuPuk+K5Qk+jBlHBlHWTunCdI=";
    };
    publisher = "vayan";
    name = "haml";
  };
  indent-rainbow = {
    pname = "indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    publisher = "oderwat";
    name = "indent-rainbow";
  };
  markdown-preview-enhanced = {
    pname = "markdown-preview-enhanced";
    version = "0.8.13";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.8.13/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.8.13.zip";
      sha256 = "sha256-DxM7oWAbIonsKTvJjxX4oTaBwvRcxNT2y10ljYAzVeI=";
    };
    publisher = "shd101wyy";
    name = "markdown-preview-enhanced";
  };
  multi-cursor-case-preserve = {
    pname = "multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    publisher = "Cardinal90";
    name = "multi-cursor-case-preserve";
  };
  nix-extension-pack = {
    pname = "nix-extension-pack";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pinage404.gallery.vsassets.io/_apis/public/gallery/publisher/pinage404/extension/nix-extension-pack/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-extension-pack-3.0.0.zip";
      sha256 = "sha256-cWXd6AlyxBroZF+cXZzzWZbYPDuOqwCZIK67cEP5sNk=";
    };
    publisher = "pinage404";
    name = "nix-extension-pack";
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.3.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.3.1.zip";
      sha256 = "sha256-05oMDHvFM/dTXB6T3rcDK3EiNG2T0tBN9Au9b+Bk7rI=";
    };
    publisher = "jnoortheen";
    name = "nix-ide";
  };
  rails-snippets = {
    pname = "rails-snippets";
    version = "1.0.8";
    src = fetchurl {
      url = "https://hridoy.gallery.vsassets.io/_apis/public/gallery/publisher/hridoy/extension/rails-snippets/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rails-snippets-1.0.8.zip";
      sha256 = "sha256-OSh/BhBxs4Vx5s8tTRlEIlk9sXRvpjLqZ6BqjGLgemA=";
    };
    publisher = "hridoy";
    name = "rails-snippets";
  };
  readable-indent = {
    pname = "readable-indent";
    version = "1.3.1";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.3.1.zip";
      sha256 = "sha256-9rIO/ikblJvLZ7FI7zLvJMDsVqzi83ino+p2MCrfQ2g=";
    };
    publisher = "cnojima";
    name = "readable-indent";
  };
  remote-ssh-edit = {
    pname = "remote-ssh-edit";
    version = "0.86.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.86.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.86.0.zip";
      sha256 = "sha256-JsbaoIekUo2nKCu+fNbGlh5d1Tt/QJGUuXUGP04TsDI=";
    };
    publisher = "ms-vscode-remote";
    name = "remote-ssh-edit";
  };
  ruby = {
    pname = "ruby";
    version = "0.1.0";
    src = fetchurl {
      url = "https://groksrc.gallery.vsassets.io/_apis/public/gallery/publisher/groksrc/extension/ruby/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-0.1.0.zip";
      sha256 = "sha256-JrkzYKjRf1bExSrZOQxek9TS+K14jcJYxjNCEqqHcdk=";
    };
    publisher = "groksrc";
    name = "ruby";
  };
  ruby-linter = {
    pname = "ruby-linter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://hoovercj.gallery.vsassets.io/_apis/public/gallery/publisher/hoovercj/extension/ruby-linter/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-linter-1.0.0.zip";
      sha256 = "sha256-DqykFLOQgv10xw/Q2ZtyW1ATOhI61+IY/6lrc9/ln3w=";
    };
    publisher = "hoovercj";
    name = "ruby-linter";
  };
  ruby-lsp = {
    pname = "ruby-lsp";
    version = "0.6.10";
    src = fetchurl {
      url = "https://Shopify.gallery.vsassets.io/_apis/public/gallery/publisher/Shopify/extension/ruby-lsp/0.6.10/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-lsp-0.6.10.zip";
      sha256 = "sha256-o4ml8OUEHQAPSYD70uWYCjQag7RvgPGVbs6FqGH7+LE=";
    };
    publisher = "Shopify";
    name = "ruby-lsp";
  };
  ruby-rubocop = {
    pname = "ruby-rubocop";
    version = "0.8.6";
    src = fetchurl {
      url = "https://misogi.gallery.vsassets.io/_apis/public/gallery/publisher/misogi/extension/ruby-rubocop/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-rubocop-0.8.6.zip";
      sha256 = "sha256-6hgJzOerGCCXcpADnISa7ewQnRWLAn6k6K4kLJR09UI=";
    };
    publisher = "misogi";
    name = "ruby-rubocop";
  };
  ruby-symbols = {
    pname = "ruby-symbols";
    version = "0.1.8";
    src = fetchurl {
      url = "https://miguel-savignano.gallery.vsassets.io/_apis/public/gallery/publisher/miguel-savignano/extension/ruby-symbols/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-symbols-0.1.8.zip";
      sha256 = "sha256-3IsqJ46IG0O2g7hKBt0OgQwruaGu9TuA3XpjAjAk550=";
    };
    publisher = "miguel-savignano";
    name = "ruby-symbols";
  };
  shell-format = {
    pname = "shell-format";
    version = "7.2.5";
    src = fetchurl {
      url = "https://foxundermoon.gallery.vsassets.io/_apis/public/gallery/publisher/foxundermoon/extension/shell-format/7.2.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "shell-format-7.2.5.zip";
      sha256 = "sha256-kfpRByJDcGY3W9+ELBzDOUMl06D/vyPlN//wPgQhByk=";
    };
    publisher = "foxundermoon";
    name = "shell-format";
  };
  simple-ruby-erb = {
    pname = "simple-ruby-erb";
    version = "0.2.1";
    src = fetchurl {
      url = "https://vortizhe.gallery.vsassets.io/_apis/public/gallery/publisher/vortizhe/extension/simple-ruby-erb/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "simple-ruby-erb-0.2.1.zip";
      sha256 = "sha256-JZov46QWUHIewu4FZtlQL/wRV6rHpu6Kd9yuWdCL77w=";
    };
    publisher = "vortizhe";
    name = "simple-ruby-erb";
  };
  solargraph = {
    pname = "solargraph";
    version = "0.24.1";
    src = fetchurl {
      url = "https://castwide.gallery.vsassets.io/_apis/public/gallery/publisher/castwide/extension/solargraph/0.24.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "solargraph-0.24.1.zip";
      sha256 = "sha256-M96kGuCKo232rIwLovDU+C/rhEgZWT4s/zsR7CUYPnk=";
    };
    publisher = "castwide";
    name = "solargraph";
  };
  tokyo-night = {
    pname = "tokyo-night";
    version = "1.0.6";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-1.0.6.zip";
      sha256 = "sha256-VWdUAU6SC7/dNDIOJmSGuIeffbwmcfeGhuSDmUE7Dig=";
    };
    publisher = "enkia";
    name = "tokyo-night";
  };
  vscode-direnv = {
    pname = "vscode-direnv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://cab404.gallery.vsassets.io/_apis/public/gallery/publisher/cab404/extension/vscode-direnv/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-direnv-1.0.0.zip";
      sha256 = "sha256-+nLH+T9v6TQCqKZw6HPN/ZevQ65FVm2SAo2V9RecM3Y=";
    };
    publisher = "cab404";
    name = "vscode-direnv";
  };
  vscode-docker = {
    pname = "vscode-docker";
    version = "1.29.1";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.29.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.29.1.zip";
      sha256 = "sha256-uleZLIkfOxKan+U56fKEwUjaleig07zdEwQKzsAzan0=";
    };
    publisher = "ms-azuretools";
    name = "vscode-docker";
  };
  vscode-emacs-friendly = {
    pname = "vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    publisher = "lfs";
    name = "vscode-emacs-friendly";
  };
  vscode-emacs-tab = {
    pname = "vscode-emacs-tab";
    version = "0.2.0";
    src = fetchurl {
      url = "https://garaemon.gallery.vsassets.io/_apis/public/gallery/publisher/garaemon/extension/vscode-emacs-tab/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-tab-0.2.0.zip";
      sha256 = "sha256-Ulwe5s/qieF7n6ymW6UdyRCUYN5LRG7pj6WyZyLNg9A=";
    };
    publisher = "garaemon";
    name = "vscode-emacs-tab";
  };
  vscode-markdownlint = {
    pname = "vscode-markdownlint";
    version = "0.55.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.55.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.55.0.zip";
      sha256 = "sha256-slfHfRPcuRu+649n6kAr2bv9H6J+DvYVN/ysq1QpPQM=";
    };
    publisher = "DavidAnson";
    name = "vscode-markdownlint";
  };
}
