[codium]
src.vsmarketplace = "Codium.codium"
fetch.vsmarketplace = "Codium.codium"
passthru = { publisher = "Codium", name = "codium"}

[copilot]
src.vsmarketplace = "GitHub.copilot"
fetch.vsmarketplace = "GitHub.copilot"
passthru = { publisher = "GitHub", name = "copilot"}

[multi-cursor-case-preserve]
src.vsmarketplace = "Cardinal90.multi-cursor-case-preserve"
fetch.vsmarketplace = "Cardinal90.multi-cursor-case-preserve"
passthru = { publisher = "Cardinal90", name = "multi-cursor-case-preserve"}

[tokyo-night]
src.vsmarketplace = "enkia.tokyo-night"
fetch.vsmarketplace = "enkia.tokyo-night"
passthru = { publisher = "enkia", name = "tokyo-night"}

[vscode-emacs-friendly]
src.vsmarketplace = "lfs.vscode-emacs-friendly"
fetch.vsmarketplace = "lfs.vscode-emacs-friendly"
passthru = { publisher = "lfs", name = "vscode-emacs-friendly"}

[readable-indent]
src.vsmarketplace = "cnojima.readable-indent"
fetch.vsmarketplace = "cnojima.readable-indent"
passthru = { publisher = "cnojima", name = "readable-indent"}

[indent-rainbow]
src.vsmarketplace = "oderwat.indent-rainbow"
fetch.vsmarketplace = "oderwat.indent-rainbow"
passthru = { publisher = "oderwat", name = "indent-rainbow"}

[vscode-markdownlint]
src.vsmarketplace = "DavidAnson.vscode-markdownlint"
fetch.vsmarketplace = "DavidAnson.vscode-markdownlint"
passthru = { publisher = "DavidAnson", name = "vscode-markdownlint"}

[markdown-preview-enhanced]
src.vsmarketplace = "shd101wyy.markdown-preview-enhanced"
fetch.vsmarketplace = "shd101wyy.markdown-preview-enhanced"
passthru = { publisher = "shd101wyy", name = "markdown-preview-enhanced"}

[vscode-docker]
src.vsmarketplace = "ms-azuretools.vscode-docker"
fetch.vsmarketplace = "ms-azuretools.vscode-docker"
passthru = { publisher = "ms-azuretools", name = "vscode-docker"}

[ruby-lsp]
src.vsmarketplace = "Shopify.ruby-lsp"
fetch.vsmarketplace ="Shopify.ruby-lsp"
passthru = { publisher = "Shopify", name = "ruby-lsp"}

# [Ruby]
# src.vsmarketplace = "rebornix.Ruby"
# fetch.vsmarketplace ="rebornix.Ruby"
# passthru = { publisher = "rebornix", name = "Ruby"}

# [vscode-ruby]
# src.vsmarketplace = "wingrunr21.vscode-ruby"
# fetch.vsmarketplace = "wingrunr21.vscode-ruby"
# passthru = { publisher = "wingrunr21", name = "vscode-ruby"}

[solargraph]
src.vsmarketplace = "castwide.solargraph"
fetch.vsmarketplace = "castwide.solargraph"
passthru = { publisher = "castwide", name = "solargraph"}

[rails-snippets]
src.vsmarketplace = "hridoy.rails-snippets"
fetch.vsmarketplace = "hridoy.rails-snippets"
passthru = { publisher = "hridoy", name = "rails-snippets"}

[ruby-rubocop]
src.vsmarketplace = "misogi.ruby-rubocop"
fetch.vsmarketplace ="misogi.ruby-rubocop"
passthru = { publisher = "misogi", name = "ruby-rubocop"}

[ruby]
src.vsmarketplace = "groksrc.ruby"
fetch.vsmarketplace = "groksrc.ruby"
passthru = { publisher = "groksrc", name = "ruby"}

[haml]
src.vsmarketplace = "vayan.haml"
fetch.vsmarketplace = "vayan.haml"
passthru = { publisher = "vayan", name = "haml"}

[simple-ruby-erb]
src.vsmarketplace = "vortizhe.simple-ruby-erb"
fetch.vsmarketplace = "vortizhe.simple-ruby-erb"
passthru = { publisher = "vortizhe", name = "simple-ruby-erb"}

[ruby-linter]
src.vsmarketplace = "hoovercj.ruby-linter"
fetch.vsmarketplace = "hoovercj.ruby-linter"
passthru = { publisher = "hoovercj", name = "ruby-linter"}

[ruby-symbols]
src.vsmarketplace = "miguel-savignano.ruby-symbols"
fetch.vsmarketplace = "miguel-savignano.ruby-symbols"
passthru = { publisher = "miguel-savignano", name = "ruby-symbols"}

[emacs-mcx]
src.vsmarketplace = "tuttieee.emacs-mcx"
fetch.vsmarketplace = "tuttieee.emacs-mcx"
passthru = { publisher = "tuttieee", name = "emacs-mcx"}

[vscode-emacs-tab]
src.vsmarketplace = "garaemon.vscode-emacs-tab"
fetch.vsmarketplace = "garaemon.vscode-emacs-tab"
passthru = { publisher = "garaemon", name = "vscode-emacs-tab"}

[remote-ssh-edit]
src.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"
fetch.vsmarketplace = "ms-vscode-remote.remote-ssh-edit"
passthru = { publisher = "ms-vscode-remote", name = "remote-ssh-edit"}

#######
[cucumberautocomplete]
src.vsmarketplace = "alexkrechik.cucumberautocomplete"
fetch.vsmarketplace = "alexkrechik.cucumberautocomplete"
passthru = { publisher = "alexkrechik", name = "cucumberautocomplete"}

[gherkintablealign]
src.vsmarketplace = "AlanCole.gherkintablealign"
fetch.vsmarketplace = "AlanCole.gherkintablealign"
passthru = { publisher = "AlanCole", name = "gherkintablealign"}

[vscode-direnv]
src.vsmarketplace = "cab404.vscode-direnv"
fetch.vsmarketplace = "cab404.vscode-direnv"
passthru = { publisher = "cab404", name = "vscode-direnv"}

[nix-extension-pack]
src.vsmarketplace = "pinage404.nix-extension-pack"
fetch.vsmarketplace = "pinage404.nix-extension-pack"
passthru = { publisher = "pinage404", name = "nix-extension-pack"}

[nix-ide]
src.vsmarketplace = "jnoortheen.nix-ide"
fetch.vsmarketplace = "jnoortheen.nix-ide"
passthru = { publisher = "jnoortheen", name = "nix-ide"}

# [even-better-toml]
# src.vsmarketplace = "tamasfe.even-better-toml"
# fetch.vsmarketplace = "tamasfe.even-better-toml"
# passthru = { publisher = "tamasfe", name = "even-better-toml"}

[shell-format]
src.vsmarketplace = "foxundermoon.shell-format"
fetch.vsmarketplace = "foxundermoon.shell-format"
passthru = { publisher = "foxundermoon", name = "shell-format"}

[bash-ide-vscode]
src.vsmarketplace = "mads-hartmann.bash-ide-vscode"
fetch.vsmarketplace = "mads-hartmann.bash-ide-vscode"
passthru = { publisher = "mads-hartmann", name = "bash-ide-vscode"}

[fonted]
src.vsmarketplace = "degreat.fonted"
fetch.vsmarketplace = "degreat.fonted"
passthru = { publisher = "degreat", name = "fonted"}
