# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  activitywatch = {
    pname = "activitywatch";
    version = "0.5.0";
    src = fetchurl {
      url = "https://activitywatch.gallery.vsassets.io/_apis/public/gallery/publisher/activitywatch/extension/aw-watcher-vscode/0.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "aw-watcher-vscode-0.5.0.zip";
      sha256 = "sha256-OrdIhgNXpEbLXYVJAx/jpt2c6Qa5jf8FNxqrbu5FfFs=";
    };
    publisher = "activitywatch";
    name = "aw-watcher-vscode";
  };
  ballerina = {
    pname = "ballerina";
    version = "4.5.23081103";
    src = fetchurl {
      url = "https://WSO2.gallery.vsassets.io/_apis/public/gallery/publisher/WSO2/extension/ballerina/4.5.23081103/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ballerina-4.5.23081103.zip";
      sha256 = "sha256-bipQKKCgwbepiBNU7xSWAzvZZ96yQuJqK6H5JdeoIXM=";
    };
    publisher = "WSO2";
    name = "ballerina";
  };
  bash-ide-vscode = {
    pname = "bash-ide-vscode";
    version = "1.39.0";
    src = fetchurl {
      url = "https://mads-hartmann.gallery.vsassets.io/_apis/public/gallery/publisher/mads-hartmann/extension/bash-ide-vscode/1.39.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bash-ide-vscode-1.39.0.zip";
      sha256 = "sha256-8tpGZ6GRnRZIwq27N8Z/NbS/ZR+FXiclcrdxcE1qVv0=";
    };
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
  };
  codium = {
    pname = "codium";
    version = "0.7.55";
    src = fetchurl {
      url = "https://Codium.gallery.vsassets.io/_apis/public/gallery/publisher/Codium/extension/codium/0.7.55/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codium-0.7.55.zip";
      sha256 = "sha256-WKpW7WA7D4UwGeCq/Eri+lAtMIjCoGJATbJYtxbCRpk=";
    };
    publisher = "Codium";
    name = "codium";
  };
  copilot = {
    pname = "copilot";
    version = "1.176.794";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.176.794/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.176.794.zip";
      sha256 = "sha256-W7MQ5yd6b7vOlNC69/6OaPh2GWl9i7lm4m4jY6XW1ns=";
    };
    publisher = "GitHub";
    name = "copilot";
  };
  crystal-lang = {
    pname = "crystal-lang";
    version = "0.9.3";
    src = fetchurl {
      url = "https://crystal-lang-tools.gallery.vsassets.io/_apis/public/gallery/publisher/crystal-lang-tools/extension/crystal-lang/0.9.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-lang-0.9.3.zip";
      sha256 = "sha256-wyfCV4JF/TdZvYmg7QGbfLnbEaqg6+2uN1BMbkpH9lI=";
    };
    publisher = "crystal-lang-tools";
    name = "crystal-lang";
  };
  crystal-spec-vscode = {
    pname = "crystal-spec-vscode";
    version = "0.1.0";
    src = fetchurl {
      url = "https://matthewmcgarvey.gallery.vsassets.io/_apis/public/gallery/publisher/matthewmcgarvey/extension/crystal-spec-vscode/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-spec-vscode-0.1.0.zip";
      sha256 = "sha256-3plr6exbkkaCSEcw766MFFI30NeQp+WNi1aAD4SpTT0=";
    };
    publisher = "matthewmcgarvey";
    name = "crystal-spec-vscode";
  };
  cucumberautocomplete = {
    pname = "cucumberautocomplete";
    version = "2.15.2";
    src = fetchurl {
      url = "https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/2.15.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cucumberautocomplete-2.15.2.zip";
      sha256 = "sha256-MdBJ71fIkIVOhLCoF/6/CATmUvutiTJPrIoVeb/eXc0=";
    };
    publisher = "alexkrechik";
    name = "cucumberautocomplete";
  };
  emacs-mcx = {
    pname = "emacs-mcx";
    version = "0.58.0";
    src = fetchurl {
      url = "https://tuttieee.gallery.vsassets.io/_apis/public/gallery/publisher/tuttieee/extension/emacs-mcx/0.58.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "emacs-mcx-0.58.0.zip";
      sha256 = "sha256-KOhaTP58wx4L3wtR9EEhQCIbhvJNKmF0NaVC8/28CPU=";
    };
    publisher = "tuttieee";
    name = "emacs-mcx";
  };
  fonted = {
    pname = "fonted";
    version = "0.0.7";
    src = fetchurl {
      url = "https://degreat.gallery.vsassets.io/_apis/public/gallery/publisher/degreat/extension/fonted/0.0.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "fonted-0.0.7.zip";
      sha256 = "sha256-mW3gC0pzMp53jx8KhkBqyFYxTIq1rcjRmfkeouZsH4A=";
    };
    publisher = "degreat";
    name = "fonted";
  };
  gherkintablealign = {
    pname = "gherkintablealign";
    version = "1.0.2";
    src = fetchurl {
      url = "https://AlanCole.gallery.vsassets.io/_apis/public/gallery/publisher/AlanCole/extension/gherkintablealign/1.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gherkintablealign-1.0.2.zip";
      sha256 = "sha256-AhCm/GyleEOW9NlzE9uSJKIjM8RKQBjSM+RS1j3jiRM=";
    };
    publisher = "AlanCole";
    name = "gherkintablealign";
  };
  gitlens = {
    pname = "gitlens";
    version = "2024.3.2805";
    src = fetchurl {
      url = "https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/2024.3.2805/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gitlens-2024.3.2805.zip";
      sha256 = "sha256-Zh2DRJlkqXIsvbKyHXQRtYwyMVaXHFsGU4dTbjBVsHQ=";
    };
    publisher = "eamodio";
    name = "gitlens";
  };
  gpt-pilot-vs-code = {
    pname = "gpt-pilot-vs-code";
    version = "0.1.12";
    src = fetchurl {
      url = "https://PythagoraTechnologies.gallery.vsassets.io/_apis/public/gallery/publisher/PythagoraTechnologies/extension/gpt-pilot-vs-code/0.1.12/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gpt-pilot-vs-code-0.1.12.zip";
      sha256 = "sha256-f+XNo3NRstKk+nc9q4qBbTehbdteDvss2MqazrlwVOQ=";
    };
    publisher = "PythagoraTechnologies";
    name = "gpt-pilot-vs-code";
  };
  haml = {
    pname = "haml";
    version = "1.0.1";
    src = fetchurl {
      url = "https://vayan.gallery.vsassets.io/_apis/public/gallery/publisher/vayan/extension/haml/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "haml-1.0.1.zip";
      sha256 = "sha256-KTsKUfo7bfwqVMSAjRYuPuk+K5Qk+jBlHBlHWTunCdI=";
    };
    publisher = "vayan";
    name = "haml";
  };
  indent-rainbow = {
    pname = "indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    publisher = "oderwat";
    name = "indent-rainbow";
  };
  julia-color-themes = {
    pname = "julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "julia-color-themes-0.1.1.zip";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    publisher = "cameronbieganek";
    name = "julia-color-themes";
  };
  language-julia = {
    pname = "language-julia";
    version = "1.75.2";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.75.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "language-julia-1.75.2.zip";
      sha256 = "sha256-wGguwyTy3jj89ud/nQw2vbtNxYuWkfi0qG6QGUyvuz4=";
    };
    publisher = "julialang";
    name = "language-julia";
  };
  markdown-preview-enhanced = {
    pname = "markdown-preview-enhanced";
    version = "0.8.13";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.8.13/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.8.13.zip";
      sha256 = "sha256-DxM7oWAbIonsKTvJjxX4oTaBwvRcxNT2y10ljYAzVeI=";
    };
    publisher = "shd101wyy";
    name = "markdown-preview-enhanced";
  };
  multi-cursor-case-preserve = {
    pname = "multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    publisher = "Cardinal90";
    name = "multi-cursor-case-preserve";
  };
  nickel-syntax = {
    pname = "nickel-syntax";
    version = "0.0.2";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nickel-syntax-0.0.2.zip";
      sha256 = "sha256-ffPZd717Y2OF4d9MWE6zKwcsGWS90ZJvhWkqP831tVM=";
    };
    publisher = "kubukoz";
    name = "nickel-syntax";
  };
  nix-extension-pack = {
    pname = "nix-extension-pack";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pinage404.gallery.vsassets.io/_apis/public/gallery/publisher/pinage404/extension/nix-extension-pack/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-extension-pack-3.0.0.zip";
      sha256 = "sha256-cWXd6AlyxBroZF+cXZzzWZbYPDuOqwCZIK67cEP5sNk=";
    };
    publisher = "pinage404";
    name = "nix-extension-pack";
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.3.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.3.1.zip";
      sha256 = "sha256-05oMDHvFM/dTXB6T3rcDK3EiNG2T0tBN9Au9b+Bk7rI=";
    };
    publisher = "jnoortheen";
    name = "nix-ide";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    publisher = "tomoki1207";
    name = "pdf";
  };
  rails-snippets = {
    pname = "rails-snippets";
    version = "1.0.8";
    src = fetchurl {
      url = "https://hridoy.gallery.vsassets.io/_apis/public/gallery/publisher/hridoy/extension/rails-snippets/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rails-snippets-1.0.8.zip";
      sha256 = "sha256-OSh/BhBxs4Vx5s8tTRlEIlk9sXRvpjLqZ6BqjGLgemA=";
    };
    publisher = "hridoy";
    name = "rails-snippets";
  };
  readable-indent = {
    pname = "readable-indent";
    version = "1.3.1";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.3.1.zip";
      sha256 = "sha256-9rIO/ikblJvLZ7FI7zLvJMDsVqzi83ino+p2MCrfQ2g=";
    };
    publisher = "cnojima";
    name = "readable-indent";
  };
  remote-ssh-edit = {
    pname = "remote-ssh-edit";
    version = "0.86.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.86.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.86.0.zip";
      sha256 = "sha256-JsbaoIekUo2nKCu+fNbGlh5d1Tt/QJGUuXUGP04TsDI=";
    };
    publisher = "ms-vscode-remote";
    name = "remote-ssh-edit";
  };
  ruby = {
    pname = "ruby";
    version = "0.1.0";
    src = fetchurl {
      url = "https://groksrc.gallery.vsassets.io/_apis/public/gallery/publisher/groksrc/extension/ruby/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-0.1.0.zip";
      sha256 = "sha256-JrkzYKjRf1bExSrZOQxek9TS+K14jcJYxjNCEqqHcdk=";
    };
    publisher = "groksrc";
    name = "ruby";
  };
  ruby-linter = {
    pname = "ruby-linter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://hoovercj.gallery.vsassets.io/_apis/public/gallery/publisher/hoovercj/extension/ruby-linter/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-linter-1.0.0.zip";
      sha256 = "sha256-DqykFLOQgv10xw/Q2ZtyW1ATOhI61+IY/6lrc9/ln3w=";
    };
    publisher = "hoovercj";
    name = "ruby-linter";
  };
  ruby-lsp = {
    pname = "ruby-lsp";
    version = "0.6.10";
    src = fetchurl {
      url = "https://Shopify.gallery.vsassets.io/_apis/public/gallery/publisher/Shopify/extension/ruby-lsp/0.6.10/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-lsp-0.6.10.zip";
      sha256 = "sha256-o4ml8OUEHQAPSYD70uWYCjQag7RvgPGVbs6FqGH7+LE=";
    };
    publisher = "Shopify";
    name = "ruby-lsp";
  };
  ruby-rubocop = {
    pname = "ruby-rubocop";
    version = "0.8.6";
    src = fetchurl {
      url = "https://misogi.gallery.vsassets.io/_apis/public/gallery/publisher/misogi/extension/ruby-rubocop/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-rubocop-0.8.6.zip";
      sha256 = "sha256-6hgJzOerGCCXcpADnISa7ewQnRWLAn6k6K4kLJR09UI=";
    };
    publisher = "misogi";
    name = "ruby-rubocop";
  };
  ruby-symbols = {
    pname = "ruby-symbols";
    version = "0.1.8";
    src = fetchurl {
      url = "https://miguel-savignano.gallery.vsassets.io/_apis/public/gallery/publisher/miguel-savignano/extension/ruby-symbols/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-symbols-0.1.8.zip";
      sha256 = "sha256-3IsqJ46IG0O2g7hKBt0OgQwruaGu9TuA3XpjAjAk550=";
    };
    publisher = "miguel-savignano";
    name = "ruby-symbols";
  };
  shell-format = {
    pname = "shell-format";
    version = "7.2.5";
    src = fetchurl {
      url = "https://foxundermoon.gallery.vsassets.io/_apis/public/gallery/publisher/foxundermoon/extension/shell-format/7.2.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "shell-format-7.2.5.zip";
      sha256 = "sha256-kfpRByJDcGY3W9+ELBzDOUMl06D/vyPlN//wPgQhByk=";
    };
    publisher = "foxundermoon";
    name = "shell-format";
  };
  simple-ruby-erb = {
    pname = "simple-ruby-erb";
    version = "0.2.1";
    src = fetchurl {
      url = "https://vortizhe.gallery.vsassets.io/_apis/public/gallery/publisher/vortizhe/extension/simple-ruby-erb/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "simple-ruby-erb-0.2.1.zip";
      sha256 = "sha256-JZov46QWUHIewu4FZtlQL/wRV6rHpu6Kd9yuWdCL77w=";
    };
    publisher = "vortizhe";
    name = "simple-ruby-erb";
  };
  solargraph = {
    pname = "solargraph";
    version = "0.24.1";
    src = fetchurl {
      url = "https://castwide.gallery.vsassets.io/_apis/public/gallery/publisher/castwide/extension/solargraph/0.24.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "solargraph-0.24.1.zip";
      sha256 = "sha256-M96kGuCKo232rIwLovDU+C/rhEgZWT4s/zsR7CUYPnk=";
    };
    publisher = "castwide";
    name = "solargraph";
  };
  tabnine-vscode = {
    pname = "tabnine-vscode";
    version = "3.81.0";
    src = fetchurl {
      url = "https://TabNine.gallery.vsassets.io/_apis/public/gallery/publisher/TabNine/extension/tabnine-vscode/3.81.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tabnine-vscode-3.81.0.zip";
      sha256 = "sha256-lJ9flBBDG275E+FvqthT7Q4z2AyTrTWhLmaw93PTreM=";
    };
    publisher = "TabNine";
    name = "tabnine-vscode";
  };
  tokyo-night = {
    pname = "tokyo-night";
    version = "1.0.6";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-1.0.6.zip";
      sha256 = "sha256-VWdUAU6SC7/dNDIOJmSGuIeffbwmcfeGhuSDmUE7Dig=";
    };
    publisher = "enkia";
    name = "tokyo-night";
  };
  vscode-direnv = {
    pname = "vscode-direnv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://cab404.gallery.vsassets.io/_apis/public/gallery/publisher/cab404/extension/vscode-direnv/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-direnv-1.0.0.zip";
      sha256 = "sha256-+nLH+T9v6TQCqKZw6HPN/ZevQ65FVm2SAo2V9RecM3Y=";
    };
    publisher = "cab404";
    name = "vscode-direnv";
  };
  vscode-docker = {
    pname = "vscode-docker";
    version = "1.29.0";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.29.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.29.0.zip";
      sha256 = "sha256-mVRsVsolXj31WhbWnt3Xml+NnIq7Q2uHhUUd1zgW42c=";
    };
    publisher = "ms-azuretools";
    name = "vscode-docker";
  };
  vscode-emacs-friendly = {
    pname = "vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    publisher = "lfs";
    name = "vscode-emacs-friendly";
  };
  vscode-emacs-tab = {
    pname = "vscode-emacs-tab";
    version = "0.2.0";
    src = fetchurl {
      url = "https://garaemon.gallery.vsassets.io/_apis/public/gallery/publisher/garaemon/extension/vscode-emacs-tab/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-tab-0.2.0.zip";
      sha256 = "sha256-Ulwe5s/qieF7n6ymW6UdyRCUYN5LRG7pj6WyZyLNg9A=";
    };
    publisher = "garaemon";
    name = "vscode-emacs-tab";
  };
  vscode-markdownlint = {
    pname = "vscode-markdownlint";
    version = "0.54.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.54.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.54.0.zip";
      sha256 = "sha256-BrPFFRspJIz1U08hPbLziCmRUeZv2NhRrTCx6qvhOJw=";
    };
    publisher = "DavidAnson";
    name = "vscode-markdownlint";
  };
  zeek = {
    pname = "zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bro-0.6.0.zip";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    publisher = "aeppert";
    name = "bro";
  };
}
