# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  activitywatch = {
    pname = "activitywatch";
    version = "0.5.0";
    src = fetchurl {
      url = "https://activitywatch.gallery.vsassets.io/_apis/public/gallery/publisher/activitywatch/extension/aw-watcher-vscode/0.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "aw-watcher-vscode-0.5.0.zip";
      sha256 = "sha256-OrdIhgNXpEbLXYVJAx/jpt2c6Qa5jf8FNxqrbu5FfFs=";
    };
    publisher = "activitywatch";
    name = "aw-watcher-vscode";
  };
  bash-ide-vscode = {
    pname = "bash-ide-vscode";
    version = "1.43.0";
    src = fetchurl {
      url = "https://mads-hartmann.gallery.vsassets.io/_apis/public/gallery/publisher/mads-hartmann/extension/bash-ide-vscode/1.43.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bash-ide-vscode-1.43.0.zip";
      sha256 = "sha256-IpJCzoYZ+L39HqBts487E00RfVnZhLa9wUYs2FIV9pQ=";
    };
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
  };
  codium = {
    pname = "codium";
    version = "0.12.4";
    src = fetchurl {
      url = "https://Codium.gallery.vsassets.io/_apis/public/gallery/publisher/Codium/extension/codium/0.12.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codium-0.12.4.zip";
      sha256 = "sha256-FR7MGmYGKuHbDCKfHkyG86LN0HvhT9fXP7bTnUB2HUw=";
    };
    publisher = "Codium";
    name = "codium";
  };
  copilot = {
    pname = "copilot";
    version = "1.246.1243";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.246.1243/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.246.1243.zip";
      sha256 = "sha256-OOzN+4cIbpzyYlNo3pI/2dayeUVjP3WCtLl3C+Unwic=";
    };
    publisher = "GitHub";
    name = "copilot";
  };
  crystal-lang = {
    pname = "crystal-lang";
    version = "0.9.6";
    src = fetchurl {
      url = "https://crystal-lang-tools.gallery.vsassets.io/_apis/public/gallery/publisher/crystal-lang-tools/extension/crystal-lang/0.9.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-lang-0.9.6.zip";
      sha256 = "sha256-nHtkJjxRH4/VZHjL9DmuJqVWaTrqR5CxCSaNTxL/Edg=";
    };
    publisher = "crystal-lang-tools";
    name = "crystal-lang";
  };
  crystal-spec-vscode = {
    pname = "crystal-spec-vscode";
    version = "0.1.0";
    src = fetchurl {
      url = "https://matthewmcgarvey.gallery.vsassets.io/_apis/public/gallery/publisher/matthewmcgarvey/extension/crystal-spec-vscode/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-spec-vscode-0.1.0.zip";
      sha256 = "sha256-3plr6exbkkaCSEcw766MFFI30NeQp+WNi1aAD4SpTT0=";
    };
    publisher = "matthewmcgarvey";
    name = "crystal-spec-vscode";
  };
  cucumberautocomplete = {
    pname = "cucumberautocomplete";
    version = "3.0.5";
    src = fetchurl {
      url = "https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/3.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cucumberautocomplete-3.0.5.zip";
      sha256 = "sha256-Tgqd4uoVgGJQKlj4JUM1CrjQhbi0qv9bAGz5NIHyofQ=";
    };
    publisher = "alexkrechik";
    name = "cucumberautocomplete";
  };
  emacs-mcx = {
    pname = "emacs-mcx";
    version = "0.62.3";
    src = fetchurl {
      url = "https://tuttieee.gallery.vsassets.io/_apis/public/gallery/publisher/tuttieee/extension/emacs-mcx/0.62.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "emacs-mcx-0.62.3.zip";
      sha256 = "sha256-iLipoayTTSt71TTyJsAaxU3GFcqoxhuCF9pa4ZZ5o58=";
    };
    publisher = "tuttieee";
    name = "emacs-mcx";
  };
  fonted = {
    pname = "fonted";
    version = "1.1.0";
    src = fetchurl {
      url = "https://degreat.gallery.vsassets.io/_apis/public/gallery/publisher/degreat/extension/fonted/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "fonted-1.1.0.zip";
      sha256 = "sha256-GqleA19TLWbAVMt8+e0XbN6od5WXueJ3LFPgvbT6hPE=";
    };
    publisher = "degreat";
    name = "fonted";
  };
  gherkintablealign = {
    pname = "gherkintablealign";
    version = "1.1.0";
    src = fetchurl {
      url = "https://AlanCole.gallery.vsassets.io/_apis/public/gallery/publisher/AlanCole/extension/gherkintablealign/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gherkintablealign-1.1.0.zip";
      sha256 = "sha256-O+GCPUqX8226q+3tS/KXcw1yL6gjTe8xSUBUQQ1kNmc=";
    };
    publisher = "AlanCole";
    name = "gherkintablealign";
  };
  gitlens = {
    pname = "gitlens";
    version = "2024.12.504";
    src = fetchurl {
      url = "https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/2024.12.504/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gitlens-2024.12.504.zip";
      sha256 = "sha256-ohTo/hvhxx2ENN9QL940NZG0gEPl+dWQ+mJMg8dWrug=";
    };
    publisher = "eamodio";
    name = "gitlens";
  };
  gpt-pilot-vs-code = {
    pname = "gpt-pilot-vs-code";
    version = "0.2.32";
    src = fetchurl {
      url = "https://PythagoraTechnologies.gallery.vsassets.io/_apis/public/gallery/publisher/PythagoraTechnologies/extension/gpt-pilot-vs-code/0.2.32/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gpt-pilot-vs-code-0.2.32.zip";
      sha256 = "sha256-7wwvx1uvx2sJymCR/VYppyjDTmcF1eGJSvXTiND2fQs=";
    };
    publisher = "PythagoraTechnologies";
    name = "gpt-pilot-vs-code";
  };
  haml = {
    pname = "haml";
    version = "1.0.1";
    src = fetchurl {
      url = "https://vayan.gallery.vsassets.io/_apis/public/gallery/publisher/vayan/extension/haml/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "haml-1.0.1.zip";
      sha256 = "sha256-KTsKUfo7bfwqVMSAjRYuPuk+K5Qk+jBlHBlHWTunCdI=";
    };
    publisher = "vayan";
    name = "haml";
  };
  indent-rainbow = {
    pname = "indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    publisher = "oderwat";
    name = "indent-rainbow";
  };
  julia-color-themes = {
    pname = "julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "julia-color-themes-0.1.1.zip";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    publisher = "cameronbieganek";
    name = "julia-color-themes";
  };
  language-julia = {
    pname = "language-julia";
    version = "1.127.2";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.127.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "language-julia-1.127.2.zip";
      sha256 = "sha256-fvJ0jO+mhepnzderoh2Pg09yF0AgYGdXQLjJCFptigY=";
    };
    publisher = "julialang";
    name = "language-julia";
  };
  markdown-preview-enhanced = {
    pname = "markdown-preview-enhanced";
    version = "0.8.15";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.8.15/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.8.15.zip";
      sha256 = "sha256-aW2Ri73xIl/1q/Yoi5qg25fjx7l55QfXAn+M+JuoN+A=";
    };
    publisher = "shd101wyy";
    name = "markdown-preview-enhanced";
  };
  multi-cursor-case-preserve = {
    pname = "multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    publisher = "Cardinal90";
    name = "multi-cursor-case-preserve";
  };
  nickel-syntax = {
    pname = "nickel-syntax";
    version = "0.0.2";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nickel-syntax-0.0.2.zip";
      sha256 = "sha256-ffPZd717Y2OF4d9MWE6zKwcsGWS90ZJvhWkqP831tVM=";
    };
    publisher = "kubukoz";
    name = "nickel-syntax";
  };
  nix-extension-pack = {
    pname = "nix-extension-pack";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pinage404.gallery.vsassets.io/_apis/public/gallery/publisher/pinage404/extension/nix-extension-pack/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-extension-pack-3.0.0.zip";
      sha256 = "sha256-cWXd6AlyxBroZF+cXZzzWZbYPDuOqwCZIK67cEP5sNk=";
    };
    publisher = "pinage404";
    name = "nix-extension-pack";
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.3.5";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.3.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.3.5.zip";
      sha256 = "sha256-hiyFZVsZkxpc2Kh0zi3NGwA/FUbetAS9khWxYesxT4s=";
    };
    publisher = "jnoortheen";
    name = "nix-ide";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    publisher = "tomoki1207";
    name = "pdf";
  };
  rails-snippets = {
    pname = "rails-snippets";
    version = "1.0.8";
    src = fetchurl {
      url = "https://hridoy.gallery.vsassets.io/_apis/public/gallery/publisher/hridoy/extension/rails-snippets/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rails-snippets-1.0.8.zip";
      sha256 = "sha256-OSh/BhBxs4Vx5s8tTRlEIlk9sXRvpjLqZ6BqjGLgemA=";
    };
    publisher = "hridoy";
    name = "rails-snippets";
  };
  readable-indent = {
    pname = "readable-indent";
    version = "1.3.1";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.3.1.zip";
      sha256 = "sha256-9rIO/ikblJvLZ7FI7zLvJMDsVqzi83ino+p2MCrfQ2g=";
    };
    publisher = "cnojima";
    name = "readable-indent";
  };
  remote-ssh-edit = {
    pname = "remote-ssh-edit";
    version = "0.87.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.87.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.87.0.zip";
      sha256 = "sha256-yeX6RAJl07d+SuYyGQFLZNcUzVKAsmPFyTKEn+y3GuM=";
    };
    publisher = "ms-vscode-remote";
    name = "remote-ssh-edit";
  };
  ruby = {
    pname = "ruby";
    version = "0.1.0";
    src = fetchurl {
      url = "https://groksrc.gallery.vsassets.io/_apis/public/gallery/publisher/groksrc/extension/ruby/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-0.1.0.zip";
      sha256 = "sha256-JrkzYKjRf1bExSrZOQxek9TS+K14jcJYxjNCEqqHcdk=";
    };
    publisher = "groksrc";
    name = "ruby";
  };
  ruby-linter = {
    pname = "ruby-linter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://hoovercj.gallery.vsassets.io/_apis/public/gallery/publisher/hoovercj/extension/ruby-linter/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-linter-1.0.0.zip";
      sha256 = "sha256-DqykFLOQgv10xw/Q2ZtyW1ATOhI61+IY/6lrc9/ln3w=";
    };
    publisher = "hoovercj";
    name = "ruby-linter";
  };
  ruby-lsp = {
    pname = "ruby-lsp";
    version = "0.8.15";
    src = fetchurl {
      url = "https://Shopify.gallery.vsassets.io/_apis/public/gallery/publisher/Shopify/extension/ruby-lsp/0.8.15/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-lsp-0.8.15.zip";
      sha256 = "sha256-Ob8iDcTT0PSH71g91aeoTcpVJ7qMaZnEix9FKYLNupQ=";
    };
    publisher = "Shopify";
    name = "ruby-lsp";
  };
  ruby-rubocop = {
    pname = "ruby-rubocop";
    version = "0.8.6";
    src = fetchurl {
      url = "https://misogi.gallery.vsassets.io/_apis/public/gallery/publisher/misogi/extension/ruby-rubocop/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-rubocop-0.8.6.zip";
      sha256 = "sha256-6hgJzOerGCCXcpADnISa7ewQnRWLAn6k6K4kLJR09UI=";
    };
    publisher = "misogi";
    name = "ruby-rubocop";
  };
  ruby-symbols = {
    pname = "ruby-symbols";
    version = "0.1.8";
    src = fetchurl {
      url = "https://miguel-savignano.gallery.vsassets.io/_apis/public/gallery/publisher/miguel-savignano/extension/ruby-symbols/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-symbols-0.1.8.zip";
      sha256 = "sha256-3IsqJ46IG0O2g7hKBt0OgQwruaGu9TuA3XpjAjAk550=";
    };
    publisher = "miguel-savignano";
    name = "ruby-symbols";
  };
  shell-format = {
    pname = "shell-format";
    version = "7.2.5";
    src = fetchurl {
      url = "https://foxundermoon.gallery.vsassets.io/_apis/public/gallery/publisher/foxundermoon/extension/shell-format/7.2.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "shell-format-7.2.5.zip";
      sha256 = "sha256-kfpRByJDcGY3W9+ELBzDOUMl06D/vyPlN//wPgQhByk=";
    };
    publisher = "foxundermoon";
    name = "shell-format";
  };
  simple-ruby-erb = {
    pname = "simple-ruby-erb";
    version = "0.2.1";
    src = fetchurl {
      url = "https://vortizhe.gallery.vsassets.io/_apis/public/gallery/publisher/vortizhe/extension/simple-ruby-erb/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "simple-ruby-erb-0.2.1.zip";
      sha256 = "sha256-JZov46QWUHIewu4FZtlQL/wRV6rHpu6Kd9yuWdCL77w=";
    };
    publisher = "vortizhe";
    name = "simple-ruby-erb";
  };
  solargraph = {
    pname = "solargraph";
    version = "0.24.1";
    src = fetchurl {
      url = "https://castwide.gallery.vsassets.io/_apis/public/gallery/publisher/castwide/extension/solargraph/0.24.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "solargraph-0.24.1.zip";
      sha256 = "sha256-M96kGuCKo232rIwLovDU+C/rhEgZWT4s/zsR7CUYPnk=";
    };
    publisher = "castwide";
    name = "solargraph";
  };
  tabnine-vscode = {
    pname = "tabnine-vscode";
    version = "3.199.0";
    src = fetchurl {
      url = "https://TabNine.gallery.vsassets.io/_apis/public/gallery/publisher/TabNine/extension/tabnine-vscode/3.199.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tabnine-vscode-3.199.0.zip";
      sha256 = "sha256-JcP0f4+0WwbHDgZ04ADmV30SAdLq+Wq6y+O0dtBx+fY=";
    };
    publisher = "TabNine";
    name = "tabnine-vscode";
  };
  tokyo-night = {
    pname = "tokyo-night";
    version = "1.0.9";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/1.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-1.0.9.zip";
      sha256 = "sha256-2EphqiRVFw5cHAfCS+wscUM5eR48W9y96LJZQH4k0l4=";
    };
    publisher = "enkia";
    name = "tokyo-night";
  };
  vscode-direnv = {
    pname = "vscode-direnv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://cab404.gallery.vsassets.io/_apis/public/gallery/publisher/cab404/extension/vscode-direnv/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-direnv-1.0.0.zip";
      sha256 = "sha256-+nLH+T9v6TQCqKZw6HPN/ZevQ65FVm2SAo2V9RecM3Y=";
    };
    publisher = "cab404";
    name = "vscode-direnv";
  };
  vscode-docker = {
    pname = "vscode-docker";
    version = "1.29.3";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.29.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.29.3.zip";
      sha256 = "sha256-z0RqFos0ZG2Id/alUBZJyroX3coTcJ+x2R8v4FD2Zcg=";
    };
    publisher = "ms-azuretools";
    name = "vscode-docker";
  };
  vscode-emacs-friendly = {
    pname = "vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    publisher = "lfs";
    name = "vscode-emacs-friendly";
  };
  vscode-emacs-tab = {
    pname = "vscode-emacs-tab";
    version = "0.2.1";
    src = fetchurl {
      url = "https://garaemon.gallery.vsassets.io/_apis/public/gallery/publisher/garaemon/extension/vscode-emacs-tab/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-tab-0.2.1.zip";
      sha256 = "sha256-zANcjqo9BOBf0EWFdJiMz8cs5g4vTVgXEd2w09wNzqk=";
    };
    publisher = "garaemon";
    name = "vscode-emacs-tab";
  };
  vscode-markdownlint = {
    pname = "vscode-markdownlint";
    version = "0.57.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.57.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.57.0.zip";
      sha256 = "sha256-5izhTYDrJyJD7A9Stmp2YJXkhJPSzOzK+QsTv3UfTL8=";
    };
    publisher = "DavidAnson";
    name = "vscode-markdownlint";
  };
  zeek = {
    pname = "zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bro-0.6.0.zip";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    publisher = "aeppert";
    name = "bro";
  };
}
