jobs:
  build_system:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-24.05
    - name: Install cachix action
      uses: cachix/cachix-action@v15
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Build system configuration
      run: nix build ".#nixosConfigurations.${{ inputs.configuration }}.config.system.build.toplevel"
name: Build x86_64 host
'on':
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
      CACHIX_SIGNING_KEY:
        required: true
