jobs:
  build_damogran:
    runs-on: ubuntu-latest-arm
    steps:
    - name: ⬆️ Checkout
      uses: actions/checkout@v4.2.2
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: '

          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

          experimental-features = nix-command flakes impure-derivations auto-allocate-uids
          cgroups

          system-features = nixos-test benchmark big-parallel kvm recursive-nix

          '
        nix_path: nixpkgs=channel:nixos-24.11
    - name: Install cachix action
      uses: cachix/cachix-action@v15
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        docker-images: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        tool-cache: true
    - name: Build damogran toplevel
      run: nix build .#nixosConfigurations.nixos-damogran.config.system.build.toplevel
name: Build damogran [aarch64-linux]
'on':
  push: null
  workflow_dispatch: null
