jobs:
  build_damogran:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-24.05
    - name: Install cachix action
      uses: cachix/cachix-action@v15
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Build damogran sdImage
      run: nix build .#nixosConfigurations.nixos-damogran.config.system.build.sdImage
    - name: Build damogran toplevel
      run: nix build .#nixosConfigurations.nixos-damogran.config.system.build.toplevel
name: Build damogran [aarch64-linux]
'on':
  push: null
  workflow_dispatch: null
