jobs:
  build_system:
    runs-on: ubuntu-latest
    steps:
    - name: ⬆ Checkout
      uses: actions/checkout@v4.2.2
    - name: ✓ Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

          experimental-features = nix-command flakes impure-derivations auto-allocate-uids
          cgroups

          system-features = nixos-test benchmark big-parallel kvm recursive-nix

          download-buffer-size = 10485760

          accept-flake-config = true

          '
        nix_path: nixpkgs=channel:nixos-24.11
    - name: ✓ Install cachix action
      uses: cachix/cachix-action@v15
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        cachixArgs: --compression-method xz --compression-level 9 --jobs 4
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: ✓ Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        docker-images: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        tool-cache: true
    - name: Build system configuration
      run: nix build --accept-flake-config ".#nixosConfigurations.${{ inputs.configuration
        }}.config.system.build.toplevel"
    - if: ${{ failure() }}
      name: ✓ Detached tmate session
      uses: mxschmitt/action-tmate@master
      with:
        limit-access-to-actor: true
        timeout-minutes: 10
name: Build x86_64 host
'on':
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
      CACHIX_SIGNING_KEY:
        required: true
