jobs:
  build_shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-23.05
      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          name: njk
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: Build shell
        run: nix develop --command "menu"
name: Testing the nixago
"on":
  push: null
  workflow_dispatch: null
