jobs:
  build_shell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-23.11
    - name: Install cachix action
      uses: cachix/cachix-action@v14
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        docker-images: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        tool-cache: true
    - name: Build devshell
      run: nix develop --command "menu"
name: Build devshell [x86_64-linux]
'on':
  push: null
  workflow_dispatch: null
