jobs:
  build_and_release_iso:
    runs-on: ubuntu-latest
    steps:
    - name: ⬆ Checkout
      uses: actions/checkout@v4.2.2
    - name: ✓ Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: 'access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

          experimental-features = nix-command flakes impure-derivations auto-allocate-uids
          cgroups

          system-features = nixos-test benchmark big-parallel kvm recursive-nix

          download-buffer-size = 10485760

          accept-flake-config = true

          '
        nix_path: nixpkgs=channel:nixos-24.11
    - name: ✓ Install cachix action
      uses: cachix/cachix-action@v15
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        cachixArgs: --compression-method xz --compression-level 9 --jobs 4
        extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
        name: njk
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: Free space
      run: df -h
    - name: Build keygen.iso
      run: nix develop --accept-flake-config --command just release
    - name: copy iso
      run: mkdir -p /home/runner/work/_temp/iso_release && cp $(cat /home/runner/work/_temp/iso_location.txt)
        /home/runner/work/_temp/iso_release/keygen-x86_64-linux.iso
    - name: Release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: /home/runner/work/_temp/iso_release/keygen-x86_64-linux.iso
        tag_name: v0.0.1
    - if: ${{ failure() }}
      name: ✓ tmate.io session
      uses: mxschmitt/action-tmate@master
      with:
        connect-timeout-seconds: 600
        limit-access-to-actor: true
name: Release keygen.iso [x86_64-linux]
'on':
  workflow_dispatch: null
